"use client";

import type { CreateEventFormValues } from "./create-event-form";
import type { ActiveEventFormConfiguration, ActiveEventFormField } from "./events.service";

type Props = { configuration: ActiveEventFormConfiguration; values: CreateEventFormValues; customValues: Record<string, string | string[] | boolean | number | null>; locationName: string; };
const coreValues: Record<string, keyof CreateEventFormValues> = { title: "title", description: "description", category: "category", subcategory: "subcategory", tags: "tags", organiser_name: "organiser_name", organiser_contact: "organiser_contact", start_date: "start_date", start_datetime: "start_date", end_date: "end_date", end_datetime: "end_date", registration_cutoff: "registration_cutoff", registration_open_at: "registration_open_at", registration_close_at: "registration_close_at", timezone: "time_zone", time_zone: "time_zone", event_type: "delivery_mode", delivery_mode: "delivery_mode", meeting_provider: "meeting_provider", meeting_link: "meeting_link", price: "price", currency: "currency", capacity: "capacity", min_participants: "min_participants", max_participants: "max_participants", primary_image: "primary_image", gallery_images: "gallery_images", videos: "videos", documents: "documents" };
function keyFor(field: ActiveEventFormField): string { return field.source === "core" ? field.core_key ?? field.stable_key ?? field.id : field.stable_key ?? field.id; }
function format(value: unknown): string { if (value === null || value === undefined || value === "") return "Not provided"; if (typeof value === "boolean") return value ? "Yes" : "No"; if (Array.isArray(value)) return value.length ? value.join(", ") : "Not provided"; if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}T/.test(value)) return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); return String(value); }
function enabled(field: ActiveEventFormField, key: string): boolean { const keys = field.composite_config?.enabled_fields ?? []; return keys.length === 0 || keys.includes(key); }

/** Displays only the current values included by the resolved Event form configuration. */
export default function ConfiguredCreateEventReview({ configuration, values, customValues, locationName }: Props) {
  return <section className="space-y-5"><div><h2 className="text-xl font-bold text-[#06201c]">Review &amp; Submit</h2><p className="mt-1 text-sm text-[#52736a]">Review the configured Event details before creating the draft.</p></div>{[...configuration.sections].filter((section) => section.is_enabled).sort((a, b) => a.position - b.position).map((section) => <div key={section.id} className="rounded-xl border border-[#edf3f0] p-4"><h3 className="font-bold text-[#06201c]">{section.label}</h3><dl className="mt-3 grid gap-3 md:grid-cols-2">{[...section.fields].sort((a, b) => a.position - b.position).map((field) => <ReviewField key={field.id} field={field} values={values} customValues={customValues} locationName={locationName} />)}</dl></div>)}</section>;
}
function ReviewField({ field, values, customValues, locationName }: { field: ActiveEventFormField; values: CreateEventFormValues; customValues: Props["customValues"]; locationName: string }) { const key = keyFor(field); if (key === "venue") return <Composite label={field.label} items={["name", "address", "city", "coordinates.lat", "coordinates.lng"].filter((name) => enabled(field, name)).map((name) => `${name}: ${format(name === "name" ? values.venue_name : name === "address" ? values.venue_address : name === "city" ? values.venue_city : name === "coordinates.lat" ? values.venue_latitude : values.venue_longitude)}`)} />; if (field.renderer === "ticket_types" || key === "ticket_types") return <Composite label={field.label} items={values.ticket_types.map((ticket) => ["name", "price", "currency", "capacity"].filter((name) => enabled(field, name)).map((name) => `${name}: ${format(ticket[name as keyof typeof ticket])}`).join(" · "))} />; if (field.renderer === "sessions" || key === "sessions") return <Composite label={field.label} items={values.sessions.map((session) => ["session_date", "title", "speaker", "start_time", "end_time", "location"].filter((name) => enabled(field, name)).map((name) => `${name}: ${format(session[name as keyof typeof session])}`).join(" · "))} />; if (field.renderer === "registration_fields" || ["custom_fields", "registration_questions", "registration_fields"].includes(key)) return <Composite label={field.label} items={values.custom_fields.map((question) => ["label", "type", "options"].filter((name) => enabled(field, name)).map((name) => `${name}: ${format(question[name as keyof typeof question])}`).join(" · "))} />; if (["location", "location_id"].includes(key)) return <Item label={field.label} value={locationName} />; const core = coreValues[key]; return <Item label={field.label} value={format(core ? values[core] : customValues[key])} />; }
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-bold uppercase tracking-wide text-[#7f9d94]">{label}</dt><dd className="mt-1 text-sm text-[#06201c]">{value}</dd></div>; }
function Composite({ label, items }: { label: string; items: string[] }) { return <div className="md:col-span-2"><dt className="text-xs font-bold uppercase tracking-wide text-[#7f9d94]">{label}</dt><dd className="mt-1 space-y-1 text-sm text-[#06201c]">{items.length ? items.map((item, index) => <p key={index}>{item}</p>) : <p>Not provided</p>}</dd></div>; }
