import { displayValue, formatEventDate, formatEventDateTime, formatEventDeliveryMode, formatEventDurationType, formatEventTime } from "./event-detail-formatters";
import type { ActiveEventFormConfiguration, ActiveEventFormField, Event } from "./events.service";

type Props = { configuration: ActiveEventFormConfiguration; event: Event; sessionsSection?: React.ReactNode };

export default function ConfiguredEventDetails({ configuration, event, sessionsSection }: Props) {
  const customValues = new Map((event.custom_values ?? []).map((item) => [item.field_id, item.value]));
  const sections = [...configuration.sections].filter((section) => section.is_enabled).sort((a, b) => a.position - b.position);
  return <>{sections.map((section) => <DetailSection key={section.id} title={section.label}>{[...section.fields].filter((field) => field.is_enabled !== false).sort((a, b) => a.position - b.position).map((field) => sessionsSection && isSessionsField(field) ? <div key={field.id} className="sm:col-span-2">{sessionsSection}</div> : <ConfiguredField key={field.id} field={field} event={event} value={field.source === "custom" ? customValues.get(field.id) : (field.core_key === "duration_type" ? event.duration_type : coreValue(field, event))} />)}</DetailSection>)}</>;
}

function DetailSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#e1ebe6] bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-[#06201c]">{title}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{children}</div></section>; }
function ConfiguredField({ field, event, value }: { field: ActiveEventFormField; event: Event; value: unknown }) { const key = field.core_key ?? field.stable_key ?? field.id; return <div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#7f9d94]">{field.label}</p><div className="mt-1 text-sm font-semibold text-[#06201c]"><ReadOnlyValue field={field} keyName={key} value={value} event={event} /></div></div>; }
function isSessionsField(field: ActiveEventFormField): boolean { const key = field.core_key ?? field.stable_key ?? field.id; return field.source === "core" && key === "sessions" && field.renderer === "sessions"; }
function ReadOnlyValue({ field, keyName, value, event }: { field: ActiveEventFormField; keyName: string; value: unknown; event: Event }) { const parsed = parseStructuredValue(value); if (keyName === "ticket_types" || field.renderer === "ticket_types") return <TicketTypes value={parsed} field={field} />; if (keyName === "sessions" || field.renderer === "sessions") return <Sessions value={parsed} field={field} timeZone={event.time_zone} />; if (["venue", "location"].includes(keyName)) return <Venue value={parsed} />; if (["custom_fields", "registration_questions", "registration_fields"].includes(keyName) || field.renderer === "registration_fields") return <RegistrationQuestions value={parsed} field={field} />; if (["primary_image", "gallery_images", "videos", "documents"].includes(keyName)) return <Media value={parsed} kind={keyName} />; return <span className="whitespace-pre-wrap break-words">{formatScalar(parsed, keyName, event)}</span>; }
function TicketTypes({ value, field }: { value: unknown; field: ActiveEventFormField }) { const items = asRecords(value); if (!items.length) return <span>—</span>; return <div className="space-y-3">{items.map((item, index) => <article key={String(item.id ?? index)} className="rounded-xl border border-[#edf3f0] bg-[#f9fcfa] p-3"><p className="font-bold">{text(item.name) || `Ticket ${index + 1}`}</p><div className="mt-1 grid gap-1 text-sm font-normal sm:grid-cols-2">{enabled(field, "price") && text(item.price) ? <span>Price: {text(item.currency) ? `${text(item.currency)} ${text(item.price)}` : text(item.price)}</span> : null}{enabled(field, "capacity") && text(item.capacity) ? <span>Capacity: {text(item.capacity)}</span> : null}</div></article>)}</div>; }
function Sessions({ value, field, timeZone }: { value: unknown; field: ActiveEventFormField; timeZone: string }) { const items = asRecords(value); if (!items.length) return <span>—</span>; return <div className="space-y-3">{items.map((item, index) => <article key={String(item.id ?? index)} className="rounded-xl border border-[#edf3f0] bg-[#f9fcfa] p-3"><p className="break-words font-bold">{text(item.title) || `Session ${index + 1}`}</p><div className="mt-1 space-y-1 text-sm font-normal">{enabled(field, "session_date") && text(item.session_date) ? <p>{formatEventDate(text(item.session_date), timeZone)}</p> : null}{enabled(field, "start_time") && (text(item.start_time) || text(item.end_time)) ? <p>{[text(item.start_time), text(item.end_time)].filter(Boolean).join(" – ")}</p> : null}{enabled(field, "speaker") && text(item.speaker) ? <p>Speaker: {text(item.speaker)}</p> : null}{enabled(field, "location") && text(item.location) ? <p>Location: {text(item.location)}</p> : null}{enabled(field, "meeting_link") && safeUrl(text(item.meeting_link)) ? <p><ExternalLink href={safeUrl(text(item.meeting_link))!} label="Meeting link" /></p> : null}</div></article>)}</div>; }
function Venue({ value }: { value: unknown }) { const item = asRecords(value)[0]; if (!item) return <span>—</span>; const coordinates = asRecords(item.coordinates)[0]; return <div className="space-y-1 font-normal">{[item.name, item.address, item.city].filter((part) => text(part)).map((part, index) => <p key={index}>{text(part)}</p>)}{coordinates && (text(coordinates.lat) || text(coordinates.lng)) ? <p>Coordinates: {[coordinates.lat, coordinates.lng].filter((part) => text(part)).join(", ")}</p> : null}</div>; }
function RegistrationQuestions({ value, field }: { value: unknown; field: ActiveEventFormField }) { const items = asRecords(value); if (!items.length) return <span>—</span>; return <div className="space-y-2">{items.map((item, index) => <div key={index}><p className="font-bold">{text(item.label) || `Question ${index + 1}`}</p>{enabled(field, "type") && text(item.type) ? <p className="font-normal">Type: {text(item.type)}</p> : null}{enabled(field, "options") && asStrings(item.options).length ? <p className="font-normal">Options: {asStrings(item.options).join(", ")}</p> : null}</div>)}</div>; }
function Media({ value, kind }: { value: unknown; kind: string }) { const values = Array.isArray(value) ? value : [value]; const links = values.map((item) => typeof item === "object" && item !== null ? asRecords(item)[0] : null).map((item, index) => ({ url: safeUrl(text(item?.url ?? item?.src ?? values[index])), title: text(item?.title) })); if (!links.some((item) => item.url)) return <span>—</span>; return <ul className="space-y-1 font-normal">{links.map((item, index) => item.url ? <li key={index}><ExternalLink href={item.url} label={item.title || `${kind} ${index + 1}`} /></li> : null)}</ul>; }
function ExternalLink({ href, label }: { href: string; label: string }) { return <a href={href} target="_blank" rel="noopener noreferrer" className="break-all text-[#1f6a58] underline">{label}</a>; }
function coreValue(field: ActiveEventFormField, event: Event): unknown { const key = field.core_key ?? field.stable_key ?? field.id; return ({ title: event.title, event_name: event.title, description: event.description, category: event.category, subcategory: event.subcategory, tags: event.tags, organiser_name: event.organiser_name, organiser_contact: event.organiser_contact, start_date: event.start_date, start_datetime: event.start_date, end_date: event.end_date, end_datetime: event.end_date, timezone: event.time_zone, time_zone: event.time_zone, registration_cutoff: event.registration_cutoff, registration_open_at: event.registration_open_at, registration_close_at: event.registration_close_at, delivery_mode: event.delivery_mode, event_type: event.delivery_mode, pricing_type: event.pricing_type ?? (Number(event.price) === 0 ? "free" : "paid"), meeting_provider: event.meeting_provider, meeting_link: event.meeting_link, price: event.price, currency: event.currency, capacity: event.capacity, min_participants: event.min_participants, max_participants: event.max_participants, primary_image: event.primary_image, gallery_images: event.gallery_images, videos: event.videos, documents: event.documents, ticket_types: event.ticket_types, sessions: event.sessions, custom_fields: event.custom_fields, venue: event.venue } as Record<string, unknown>)[key]; }
function parseStructuredValue(value: unknown): unknown { if (typeof value !== "string") return value; const trimmed = value.trim(); if (!(trimmed.startsWith("[") || trimmed.startsWith("{"))) return value; try { return JSON.parse(trimmed) as unknown; } catch { return value; } }
function formatScalar(value: unknown, key: string, event: Event): string { if (value === null || value === undefined || value === "") return "—"; if (key === "duration_type") return formatEventDurationType(String(value)); if (key === "delivery_mode" || key === "event_type") return formatEventDeliveryMode(String(value)); if (["start_date", "start_datetime"].includes(key)) return `${formatEventDate(event.start_date, event.time_zone)} · ${formatEventTime(event.start_date, event.time_zone)}`; if (["end_date", "end_datetime"].includes(key)) return `${formatEventDate(event.end_date, event.time_zone)} · ${formatEventTime(event.end_date, event.time_zone)}`; if (["registration_cutoff", "registration_open_at", "registration_close_at"].includes(key)) return formatEventDateTime(String(value), event.time_zone); if (typeof value === "boolean") return value ? "Yes" : "No"; if (Array.isArray(value)) return value.length ? value.map((item) => typeof item === "object" ? readableObject(item) : String(item)).join(", ") : "—"; if (typeof value === "object") return readableObject(value); return displayValue(value as string | number); }
function readableObject(value: unknown): string { const item = asRecords(value)[0]; if (!item) return "—"; return Object.entries(item).filter(([, part]) => part !== null && part !== undefined && part !== "" && !Array.isArray(part) && typeof part !== "object").map(([key, part]) => `${key}: ${String(part)}`).join(" · ") || "—"; }
function asRecords(value: unknown): Array<Record<string, unknown>> { if (Array.isArray(value)) return value.filter((item): item is Record<string, unknown> => typeof item === "object" && item !== null && !Array.isArray(item)); if (typeof value === "object" && value !== null) return [value as Record<string, unknown>]; return []; }
function asStrings(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function text(value: unknown): string { return value === null || value === undefined ? "" : String(value).trim(); }
function enabled(field: ActiveEventFormField, name: string): boolean { return !field.composite_config?.enabled_fields || field.composite_config.enabled_fields.includes(name); }
function safeUrl(value: string): string | null { try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:" ? url.toString() : null; } catch { return null; } }
