"use client";

import type { CreateEventFormValues, EventCustomFieldFormValue, EventTicketFormValue } from "./create-event-form";
import type { EventSessionInput } from "./events.service";
import { formatSessionDate, getEventSessionDates, getSessionTimeBounds } from "./event-session-date";

type UpdateForm = <Key extends keyof CreateEventFormValues>(key: Key, value: CreateEventFormValues[Key]) => void;
type SectionProps = { values: CreateEventFormValues; update: UpdateForm; errors: Record<string, string[]> };
const inputClass = "mt-1.5 h-11 w-full rounded-xl border border-[#d7e5df] bg-[#f9fcfa] px-3 text-sm text-[#06201c] outline-none focus:border-[#1f6a58]";
const labelClass = "block text-sm font-semibold text-[#06201c]";

/** Renders the primary price and structured ticket-type editor. */
export function PricingAndTicketsSection({ values, update, errors }: SectionProps) {
  const patchTicket = (index: number, field: keyof EventTicketFormValue, value: string) => update("ticket_types", values.ticket_types.map((ticket, current) => current === index ? { ...ticket, [field]: value } : ticket));
  return <section className="space-y-5"><Heading title="Pricing & Tickets" description="Add the primary price and any available ticket types." />
    <div className="grid gap-4 md:grid-cols-2"><Field label="Price" value={values.price} onChange={(value) => update("price", value)} type="number" error={errors.price} /><Field label="Currency" value={values.currency} onChange={(value) => update("currency", value)} error={errors.currency} /></div>
    <div className="flex items-center justify-between"><h3 className="text-base font-bold text-[#06201c]">Ticket types</h3><button type="button" onClick={() => update("ticket_types", [...values.ticket_types, { id: "", name: "", price: "", currency: values.currency, capacity: "" }])} className="rounded-full border border-[#d7e5df] px-4 py-2 text-sm font-semibold text-[#1f6a58]">+ Add Ticket Type</button></div>
    {errors.ticket_types?.[0] ? <p className="text-xs font-medium text-[#b42318]">{errors.ticket_types[0]}</p> : null}
    {values.ticket_types.map((ticket, index) => <div key={index} className="grid gap-3 rounded-2xl border border-[#edf3f0] bg-[#f9fcfa] p-4 md:grid-cols-2"><Field label="Ticket ID" value={ticket.id} onChange={(value) => patchTicket(index, "id", value)} /><Field label="Name" value={ticket.name} onChange={(value) => patchTicket(index, "name", value)} /><Field label="Price" value={ticket.price} onChange={(value) => patchTicket(index, "price", value)} type="number" /><Field label="Currency" value={ticket.currency} onChange={(value) => patchTicket(index, "currency", value)} /><Field label="Capacity" value={ticket.capacity} onChange={(value) => patchTicket(index, "capacity", value)} type="number" /><button type="button" onClick={() => update("ticket_types", values.ticket_types.filter((_, current) => current !== index))} className="self-end rounded-full border border-[#f3d0cb] px-4 py-2 text-sm font-semibold text-[#b42318]">Remove</button></div>)}
  </section>;
}

/** Renders capacity limits and registration capacity inputs. */
export function CapacityAndRegistrationSection({ values, update, errors }: SectionProps) {
  return <section className="space-y-5"><Heading title="Capacity & Registration" description="Set the attendance boundaries for this event." /><div className="grid gap-4 md:grid-cols-3"><Field label="Overall capacity" value={values.capacity} onChange={(value) => update("capacity", value)} type="number" error={errors.capacity} /><Field label="Minimum participants" value={values.min_participants} onChange={(value) => update("min_participants", value)} type="number" error={errors.min_participants} /><Field label="Maximum participants" value={values.max_participants} onChange={(value) => update("max_participants", value)} type="number" error={errors.max_participants} /></div></section>;
}

/** Renders URL-based images and media lists without fabricating uploads. */
export function MediaSection({ values, update, errors }: SectionProps) {
  return <section className="space-y-5"><Heading title="Images & Media" description="Add hosted URLs. Uploads are not configured in this workspace." /><Field label="Primary image URL" value={values.primary_image} onChange={(value) => update("primary_image", value)} type="url" error={errors.media} /><UrlList label="Gallery images" values={values.gallery_images} update={(next) => update("gallery_images", next)} /><UrlList label="Videos" values={values.videos} update={(next) => update("videos", next)} /><UrlList label="Documents" values={values.documents} update={(next) => update("documents", next)} /></section>;
}

/** Renders included sessions and supported custom registration fields. */
export function AdditionalConfigurationSection({ values, update, errors }: SectionProps) {
  const sessionDates = getEventSessionDates(values.start_date, values.end_date);
  const patchSession = (index: number, field: keyof EventSessionInput, value: string) => update("sessions", values.sessions.map((session, current) => current === index ? { ...session, [field]: value } : session));
  const patchCustom = (index: number, field: keyof EventCustomFieldFormValue, value: string | string[]) => update("custom_fields", values.custom_fields.map((custom, current) => current === index ? { ...custom, [field]: value } as EventCustomFieldFormValue : custom));
  return <section className="space-y-7"><div><Heading title="Additional Configuration" description="Include sessions and custom registration fields in this create request." /></div>
    <RepeaterHeading title="Sessions" action="+ Add Session" onClick={() => update("sessions", [...values.sessions, { session_date: sessionDates.length === 1 ? sessionDates[0] : "", title: "", speaker: "", start_time: "", end_time: "", location: "" }])} />
    {errors.sessions?.[0] ? <p className="text-xs font-medium text-[#b42318]">{errors.sessions[0]}</p> : null}
    {values.sessions.map((session, index) => { const bounds = getSessionTimeBounds(session.session_date, values.start_date, values.end_date); return <div key={index} className="grid gap-3 rounded-2xl border border-[#edf3f0] bg-[#f9fcfa] p-4 md:grid-cols-2"><label className={labelClass}>Session date *<select value={session.session_date} onChange={(event) => patchSession(index, "session_date", event.target.value)} className={inputClass}><option value="" disabled>Select a date</option>{sessionDates.map((date) => <option key={date} value={date}>{formatSessionDate(date)}</option>)}</select></label><Field label="Session title" value={session.title} onChange={(value) => patchSession(index, "title", value)} /><Field label="Speaker" value={session.speaker} onChange={(value) => patchSession(index, "speaker", value)} /><Field label="Start time" value={session.start_time} onChange={(value) => patchSession(index, "start_time", value)} type="time" min={bounds.min} max={bounds.max} /><Field label="End time" value={session.end_time} onChange={(value) => patchSession(index, "end_time", value)} type="time" min={bounds.min} max={bounds.max} /><Field label="Location" value={session.location} onChange={(value) => patchSession(index, "location", value)} /><button type="button" onClick={() => update("sessions", values.sessions.filter((_, current) => current !== index))} className="self-end rounded-full border border-[#f3d0cb] px-4 py-2 text-sm font-semibold text-[#b42318]">Remove</button></div>})}
    <RepeaterHeading title="Custom registration fields" action="+ Add Custom Field" onClick={() => update("custom_fields", [...values.custom_fields, { label: "", type: "select", options: [] }])} />
    {errors.custom_fields?.[0] ? <p className="text-xs font-medium text-[#b42318]">{errors.custom_fields[0]}</p> : null}
    {values.custom_fields.map((custom, index) => <div key={index} className="grid gap-3 rounded-2xl border border-[#edf3f0] bg-[#f9fcfa] p-4 md:grid-cols-2"><Field label="Field label" value={custom.label} onChange={(value) => patchCustom(index, "label", value)} /><label className={labelClass}>Field type<select value={custom.type} className={inputClass} disabled><option value={custom.type}>{custom.type}</option></select></label><Field label="Options (comma separated)" value={custom.options.join(", ")} onChange={(value) => patchCustom(index, "options", value.split(",").map((item) => item.trim()).filter(Boolean))} /><button type="button" onClick={() => update("custom_fields", values.custom_fields.filter((_, current) => current !== index))} className="self-end rounded-full border border-[#f3d0cb] px-4 py-2 text-sm font-semibold text-[#b42318]">Remove</button></div>)}
  </section>;
}

/** Renders the concise final review of the Event that will be created. */
export function ReviewSection({ values, selectedLocationName }: { values: CreateEventFormValues; selectedLocationName: string }) {
  return <section className="space-y-5"><Heading title="Review & Submit" description="Review the draft before creating the event." /><div className="grid gap-4 md:grid-cols-2"><ReviewItem label="Event" value={values.title || "Not provided"} /><ReviewItem label="Organizer" value={values.organiser_name || "Not provided"} /><ReviewItem label="Schedule" value={`${values.start_date || "Not provided"} — ${values.end_date || "Not provided"}`} /><ReviewItem label="Location" value={selectedLocationName || "Not selected"} /><ReviewItem label="Price" value={`${values.price || "Not provided"} ${values.currency}`} /><ReviewItem label="Capacity" value={values.capacity || "Not provided"} /><ReviewItem label="Media" value={`${values.gallery_images.length} gallery, ${values.videos.length} videos, ${values.documents.length} documents`} /><ReviewItem label="Sessions" value={`${values.sessions.length} included`} /></div></section>;
}

function UrlList({ label, values, update }: { label: string; values: string[]; update: (values: string[]) => void }) { return <div><div className="flex items-center justify-between"><p className={labelClass}>{label}</p><button type="button" onClick={() => update([...values, ""])} className="text-sm font-semibold text-[#1f6a58]">+ Add</button></div><div className="mt-2 space-y-2">{values.map((value, index) => <div key={index} className="flex gap-2"><input type="url" value={value} onChange={(event) => update(values.map((current, item) => item === index ? event.target.value : current))} className={inputClass.replace("mt-1.5 ", "")} /><button type="button" onClick={() => update(values.filter((_, item) => item !== index))} className="rounded-xl px-3 text-sm font-semibold text-[#b42318]">Remove</button></div>)}</div></div>; }
function Heading({ title, description }: { title: string; description: string }) { return <div><h2 className="text-xl font-bold text-[#06201c]">{title}</h2><p className="mt-1 text-sm text-[#52736a]">{description}</p></div>; }
function RepeaterHeading({ title, action, onClick }: { title: string; action: string; onClick: () => void }) { return <div className="flex items-center justify-between"><h3 className="text-base font-bold text-[#06201c]">{title}</h3><button type="button" onClick={onClick} className="rounded-full border border-[#d7e5df] px-4 py-2 text-sm font-semibold text-[#1f6a58]">{action}</button></div>; }
function Field({ label, value, onChange, type = "text", min, max, error }: { label: string; value: string; onChange: (value: string) => void; type?: string; min?: string; max?: string; error?: string[] }) { return <label className={labelClass}>{label}<input type={type} value={value} min={min} max={max} onChange={(event) => onChange(event.target.value)} className={inputClass} />{error?.[0] ? <p className="mt-1 text-xs font-medium text-[#b42318]">{error[0]}</p> : null}</label>; }
function ReviewItem({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-[#edf3f0] bg-[#f9fcfa] p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#7f9d94]">{label}</p><p className="mt-1 text-sm font-semibold text-[#06201c]">{value}</p></div>; }
