"use client";

import type { CreateEventFormValues, EventCustomFieldFormValue, EventTicketFormValue } from "./create-event-form";
import SessionTableEditor, { type SessionGenerationRule } from "./SessionTableEditor";
import EventMediaEditor from "./EventMediaEditor";
import type { EventMediaField, EventMediaPolicy, EventMediaUploadState } from "./event-media";

type UpdateForm = <Key extends keyof CreateEventFormValues>(key: Key, value: CreateEventFormValues[Key]) => void;
type SectionProps = { values: CreateEventFormValues; update: UpdateForm; errors: Record<string, string[]>; mediaPolicy?: EventMediaPolicy; policyError?: string; uploads?: readonly EventMediaUploadState[]; onMediaLinkChange?: (field: EventMediaField, index: number, value: string) => void; onMediaAddLink?: (field: EventMediaField) => void; onMediaRemove?: (field: EventMediaField, index: number) => void; onMediaUpload?: (field: EventMediaField, file: File, replaceIndex?: number) => void; onMediaRetry?: (uploadId: string) => void; onMediaUploadRemove?: (uploadId: string) => void; sessionGenerationRules?: readonly SessionGenerationRule[]; onSessionGenerationRulesChange?: (rules: SessionGenerationRule[]) => void };
const inputClass = "mt-1.5 h-11 w-full rounded-xl border border-[#d7e5df] bg-[#f9fcfa] px-3 text-sm text-[#06201c] outline-none focus:border-[#1f6a58]";
const labelClass = "block text-sm font-semibold text-[#06201c]";

/** Renders the primary price and structured ticket-type editor. */
export function PricingAndTicketsSection({ values, update, errors }: SectionProps) {
  const patchTicket = (index: number, field: keyof EventTicketFormValue, value: string) => update("ticket_types", values.ticket_types.map((ticket, current) => current === index ? { ...ticket, [field]: value } : ticket));
  if (values.pricing_type === "free") return <section className="space-y-5"><Heading title="Pricing & Tickets" description="This Event is free." /><label className={labelClass}>Pricing Type<select value={values.pricing_type} onChange={(event) => update("pricing_type", event.target.value as CreateEventFormValues["pricing_type"])} className={inputClass}><option value="free">Free</option><option value="paid">Paid</option></select></label></section>;
  return <section className="space-y-5"><Heading title="Pricing & Tickets" description="Add the primary price and any available ticket types." /><label className={labelClass}>Pricing Type<select value={values.pricing_type} onChange={(event) => update("pricing_type", event.target.value as CreateEventFormValues["pricing_type"])} className={inputClass}><option value="free">Free</option><option value="paid">Paid</option></select></label>
    <div className="grid gap-4 md:grid-cols-2"><Field id="price" label="Price" value={values.price} onChange={(value) => update("price", value)} type="number" error={errors.price} /><Field id="currency" label="Currency" value={values.currency} onChange={(value) => update("currency", value)} error={errors.currency} /></div>
    <div className="flex items-center justify-between"><h3 className="text-base font-bold text-[#06201c]">Ticket types</h3><button type="button" onClick={() => update("ticket_types", [...values.ticket_types, { id: "", name: "", price: "", currency: values.currency, capacity: "" }])} className="rounded-full border border-[#d7e5df] px-4 py-2 text-sm font-semibold text-[#1f6a58]">+ Add Ticket Type</button></div>
    {errors.ticket_types?.[0] ? <p className="text-xs font-medium text-[#b42318]">{errors.ticket_types[0]}</p> : null}
    {values.ticket_types.map((ticket, index) => <div key={index} className="grid gap-3 rounded-2xl border border-[#edf3f0] bg-[#f9fcfa] p-4 md:grid-cols-2"><Field label="Ticket ID" value={ticket.id} onChange={(value) => patchTicket(index, "id", value)} /><Field label="Name" value={ticket.name} onChange={(value) => patchTicket(index, "name", value)} /><Field label="Price" value={ticket.price} onChange={(value) => patchTicket(index, "price", value)} type="number" /><Field label="Currency" value={ticket.currency} onChange={(value) => patchTicket(index, "currency", value)} /><Field label="Capacity" value={ticket.capacity} onChange={(value) => patchTicket(index, "capacity", value)} type="number" /><button type="button" onClick={() => update("ticket_types", values.ticket_types.filter((_, current) => current !== index))} className="self-end rounded-full border border-[#f3d0cb] px-4 py-2 text-sm font-semibold text-[#b42318] transition-colors hover:bg-[#fff1f0] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#b42318]">Remove</button></div>)}
  </section>;
}

/** Renders capacity limits and registration capacity inputs. */
export function CapacityAndRegistrationSection({ values, update, errors }: SectionProps) {
  return <section className="space-y-5"><Heading title="Capacity & Registration" description="Set the attendance boundaries for this event." /><div className="grid gap-4 md:grid-cols-3"><Field id="capacity" label="Overall capacity" value={values.capacity} onChange={(value) => update("capacity", value)} type="number" min="0" error={errors.capacity} /><Field id="min_participants" label="Minimum participants" value={values.min_participants} onChange={(value) => update("min_participants", value)} type="number" min="0" error={errors.min_participants} /><Field id="max_participants" label="Maximum participants" value={values.max_participants} onChange={(value) => update("max_participants", value)} type="number" min="0" error={errors.max_participants} /></div></section>;
}

/** Renders URL-based images and media lists without fabricating uploads. */
export function MediaSection({ values, errors, mediaPolicy, policyError, uploads = [], onMediaLinkChange, onMediaAddLink, onMediaRemove, onMediaUpload, onMediaRetry, onMediaUploadRemove }: SectionProps) {
  const linkChange = onMediaLinkChange ?? (() => undefined);
  const addLink = onMediaAddLink ?? (() => undefined);
  const remove = onMediaRemove ?? (() => undefined);
  const upload = onMediaUpload ?? (() => undefined);
  const retry = onMediaRetry ?? (() => undefined); const removeUpload = onMediaUploadRemove ?? (() => undefined);
  return <section className="min-w-0 space-y-5"><Heading title="Images & Media" description="Paste a public link or upload a local file. Uploads start immediately and keep their order." /><div className="space-y-5"><EventMediaEditor field="primary_image" label="Primary Image" value={values.primary_image} error={errors.primary_image?.[0] ?? errors.media?.[0]} policy={mediaPolicy} policyError={policyError} uploads={uploads} onLinkChange={(index, value) => linkChange("primary_image", index, value)} onAddLink={() => addLink("primary_image")} onRemove={(index) => remove("primary_image", index)} onUpload={(file, index) => upload("primary_image", file, index)} onRetry={retry} onUploadRemove={removeUpload} /><EventMediaEditor field="gallery_images" label="Gallery Images" value={values.gallery_images} error={errors.gallery_images?.[0] ?? errors.media?.[0]} policy={mediaPolicy} policyError={policyError} uploads={uploads} onLinkChange={(index, value) => linkChange("gallery_images", index, value)} onAddLink={() => addLink("gallery_images")} onRemove={(index) => remove("gallery_images", index)} onUpload={(file) => upload("gallery_images", file)} onRetry={retry} onUploadRemove={removeUpload} /><EventMediaEditor field="videos" label="Videos" value={values.videos} error={errors.videos?.[0] ?? errors.media?.[0]} policy={mediaPolicy} policyError={policyError} uploads={uploads} onLinkChange={(index, value) => linkChange("videos", index, value)} onAddLink={() => addLink("videos")} onRemove={(index) => remove("videos", index)} onUpload={(file) => upload("videos", file)} onRetry={retry} onUploadRemove={removeUpload} /><EventMediaEditor field="documents" label="Documents" value={values.documents} error={errors.documents?.[0] ?? errors.media?.[0]} policy={mediaPolicy} policyError={policyError} uploads={uploads} onLinkChange={(index, value) => linkChange("documents", index, value)} onAddLink={() => addLink("documents")} onRemove={(index) => remove("documents", index)} onUpload={(file) => upload("documents", file)} onRetry={retry} onUploadRemove={removeUpload} /></div></section>;
}

/** Renders included sessions and supported custom registration fields. */
export function AdditionalConfigurationSection({ values, update, errors, sessionGenerationRules, onSessionGenerationRulesChange }: SectionProps) {
  const patchCustom = (index: number, field: keyof EventCustomFieldFormValue, value: string | string[]) => update("custom_fields", values.custom_fields.map((custom, current) => current === index ? { ...custom, [field]: value } as EventCustomFieldFormValue : custom));
  return <section className="space-y-7"><div><Heading title="Additional Configuration" description="Include sessions and custom registration fields in this create request." /></div>
    <SessionTableEditor mode="create" eventStart={values.start_date} eventEnd={values.end_date} sessions={values.sessions} deliveryMode={values.delivery_mode} error={errors.sessions?.[0]} generationRules={sessionGenerationRules} onGenerationRulesChange={onSessionGenerationRulesChange} onSessionsChange={(sessions) => update("sessions", sessions)} />
    <RepeaterHeading title="Custom registration fields" action="+ Add Custom Field" onClick={() => update("custom_fields", [...values.custom_fields, { label: "", type: "select", options: [] }])} />
    {errors.custom_fields?.[0] ? <p className="text-xs font-medium text-[#b42318]">{errors.custom_fields[0]}</p> : null}
    {values.custom_fields.map((custom, index) => <div key={index} className="grid gap-3 rounded-2xl border border-[#edf3f0] bg-[#f9fcfa] p-4 md:grid-cols-2"><Field label="Field label" value={custom.label} onChange={(value) => patchCustom(index, "label", value)} /><label className={labelClass}>Field type<select value={custom.type} className={inputClass} disabled><option value={custom.type}>{custom.type}</option></select></label><Field label="Options (comma separated)" value={custom.options.join(", ")} onChange={(value) => patchCustom(index, "options", value.split(",").map((item) => item.trim()).filter(Boolean))} /><button type="button" onClick={() => update("custom_fields", values.custom_fields.filter((_, current) => current !== index))} className="self-end rounded-full border border-[#f3d0cb] px-4 py-2 text-sm font-semibold text-[#b42318]">Remove</button></div>)}
  </section>;
}

/** Renders the concise final review of the Event that will be created. */
export function ReviewSection({ values }: { values: CreateEventFormValues }) {
  if (values.pricing_type === "free") return <section className="space-y-5"><Heading title="Review & Submit" description="Review the draft before creating the event." /><div className="grid gap-4 md:grid-cols-2"><ReviewItem label="Event" value={values.title || "Not provided"} /><ReviewItem label="Organizer" value={values.organiser_name || "Not provided"} /><ReviewItem label="Pricing Type" value="Free" /><ReviewItem label="Schedule" value={`${values.start_date || "Not provided"} — ${values.end_date || "Not provided"}`} /><ReviewItem label="Capacity" value={values.capacity || "Not provided"} /><ReviewItem label="Media" value={`${values.gallery_images.length} gallery, ${values.videos.length} videos, ${values.documents.length} documents`} /><ReviewItem label="Sessions" value={`${values.sessions.length} included`} /></div></section>;
  return <section className="space-y-5"><Heading title="Review & Submit" description="Review the draft before creating the event." /><div className="grid gap-4 md:grid-cols-2"><ReviewItem label="Event" value={values.title || "Not provided"} /><ReviewItem label="Organizer" value={values.organiser_name || "Not provided"} /><ReviewItem label="Schedule" value={`${values.start_date || "Not provided"} — ${values.end_date || "Not provided"}`} /><ReviewItem label="Price" value={`${values.price || "Not provided"} ${values.currency}`} /><ReviewItem label="Capacity" value={values.capacity || "Not provided"} /><ReviewItem label="Media" value={`${values.gallery_images.length} gallery, ${values.videos.length} videos, ${values.documents.length} documents`} /><ReviewItem label="Sessions" value={`${values.sessions.length} included`} /></div></section>;
}

function Heading({ title, description }: { title: string; description: string }) { return <div><h2 className="text-xl font-bold text-[#06201c]">{title}</h2><p className="mt-1 text-sm text-[#52736a]">{description}</p></div>; }
function RepeaterHeading({ title, action, onClick }: { title: string; action: string; onClick: () => void }) { return <div className="flex items-center justify-between"><h3 className="text-base font-bold text-[#06201c]">{title}</h3><button type="button" onClick={onClick} className="rounded-full border border-[#d7e5df] px-4 py-2 text-sm font-semibold text-[#1f6a58]">{action}</button></div>; }
function Field({ id, label, value, onChange, type = "text", min, max, error }: { id?: string; label: string; value: string; onChange: (value: string) => void; type?: string; min?: string; max?: string; error?: string[] }) { const inputId = id ? `event-field-${id}` : undefined; return <label className={labelClass}>{label}<input id={inputId} type={type} value={value} min={min} max={max} aria-invalid={error?.length ? true : undefined} aria-describedby={error?.length && inputId ? `${inputId}-error` : undefined} onChange={(event) => onChange(event.target.value)} className={inputClass} />{error?.[0] ? <p id={inputId ? `${inputId}-error` : undefined} role="alert" className="mt-1 text-xs font-medium text-[#b42318]">{error[0]}</p> : null}</label>; }
function ReviewItem({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-[#edf3f0] bg-[#f9fcfa] p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#7f9d94]">{label}</p><p className="mt-1 text-sm font-semibold text-[#06201c]">{value}</p></div>; }
