"use client";

import { useQuery } from "@tanstack/react-query";
import { getEventDashboard, type Event, type EventDashboard } from "./events.service";

type EventOverviewSectionProps = { event: Event; timeZone: string; operationalDataEnabled: boolean; onViewDetails: () => void; onViewRegistrations: () => void };

/** Renders the Event overview from the backend-authoritative dashboard summary. */
export default function EventOverviewSection({ event, timeZone, operationalDataEnabled, onViewDetails, onViewRegistrations }: EventOverviewSectionProps) {
  const dashboardQuery = useQuery({ queryKey: ["events", "dashboard", event.id], queryFn: () => getEventDashboard(event.id), enabled: operationalDataEnabled && Boolean(event.id), staleTime: 30_000, retry: 1 });
  if (!operationalDataEnabled) return <div className="space-y-5"><LifecycleNotice event={event} /></div>;
  if (dashboardQuery.isLoading) return <div className="space-y-5" role="status" aria-label="Loading Event overview"><div className="h-32 animate-pulse rounded-2xl bg-[#edf3f0]" /><div className="h-48 animate-pulse rounded-2xl bg-[#edf3f0]" /></div>;
  if (dashboardQuery.isError || !dashboardQuery.data) return <div className="space-y-5"><LifecycleNotice event={event} /><section className="rounded-2xl border border-[#f0d5d1] bg-[#fff8f7] p-5"><p className="font-bold text-[#8f241b]">Unable to load the Event overview.</p><p className="mt-1 text-sm text-[#8f241b]">The Event detail page is still available. Try again to reload dashboard metrics.</p><button type="button" onClick={() => void dashboardQuery.refetch()} className="mt-3 text-sm font-bold text-[#8f241b] underline">Try again</button></section></div>;
  const dashboard = dashboardQuery.data;
  const modules = event.modules;
  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MetricCard icon="◉" label="Registrations" value={dashboard.registrations.total} supporting="Total registered" /><MetricCard icon="✓" label="Checked In" value={dashboard.attendance.checked_in} supporting={formatPercentage(dashboard.attendance.attendance_percentage, "Attendance recorded")} /><MetricCard icon="□" label="Available Seats" value={dashboard.capacity.unlimited ? "Unlimited" : dashboard.capacity.available_seats ?? "—"} supporting={dashboard.capacity.unlimited ? "No capacity limit" : formatPercentage(dashboard.capacity.fill_percentage, "Capacity unavailable", " used")} /><MetricCard icon="♡" label="Waitlist" value={dashboard.waitlist.total} supporting={dashboard.waitlist.total === 0 ? "No attendees waiting" : "Waiting for confirmation"} /><MetricCard icon="¤" label="Revenue" value={formatRevenue(dashboard.revenue)} supporting={`${dashboard.orders.successful.toLocaleString()} successful orders`} /></div>
    <LifecycleNotice event={event} />
    <section className="rounded-2xl border border-[#e1ebe6] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#7f9d94]">Event summary</p><h2 className="mt-1 text-lg font-bold text-[#06201c]">Registration and attendance</h2></div><button type="button" onClick={onViewRegistrations} className="text-sm font-semibold text-[#1f6a58] underline">View all registrations</button></div><div className="mt-4 grid gap-5 lg:grid-cols-2"><AttendanceVisual dashboard={dashboard} /><RegistrationStatusVisual dashboard={dashboard} /></div></section>
    <div className="grid gap-5 xl:grid-cols-2"><RegistrationSummary dashboard={dashboard} onViewAll={onViewRegistrations} /><SessionsSummary dashboard={dashboard} timeZone={timeZone} onViewDetails={onViewDetails} enabled={modules?.sessions !== false} /></div>
    <div className="grid gap-5 md:grid-cols-2"><CapacityVisual dashboard={dashboard} /><OrderSummary dashboard={dashboard} /></div>
    {modules?.meals !== false && dashboard.meals.length > 0 ? <OptionSummary title="Meals" items={dashboard.meals.map((item) => ({ id: item.meal_id, name: item.name, count: item.selected_count, active: item.active, price: item.price, currency: item.currency, capacity: item.capacity, reserved: item.reserved_count, remaining: item.remaining_capacity, soldOut: item.sold_out }))} /> : null}
    {modules?.accommodation !== false && dashboard.accommodation.length > 0 ? <OptionSummary title="Accommodation" items={dashboard.accommodation.map((item) => ({ id: item.accommodation_id, name: item.name, count: item.selected_count, active: item.active, price: item.price, currency: item.currency, capacity: item.capacity, reserved: item.reserved_count, remaining: item.remaining_capacity, soldOut: item.sold_out }))} /> : null}
  </div>;
}

function MetricCard({ icon, label, value, supporting }: { icon: string; label: string; value: string | number; supporting: string }) { return <article className="rounded-2xl border border-[#e1ebe6] bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><span aria-hidden="true" className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#e8f6ee] text-sm font-bold text-[#1f6a58]">{icon}</span><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#7f9d94]">{label}</p></div><p className="mt-3 text-2xl font-bold text-[#1f6a58]">{typeof value === "number" ? value.toLocaleString() : value}</p><p className="mt-1 text-xs text-[#52736a]">{supporting}</p></article>; }
function LifecycleNotice({ event }: { event: Event }) { return event.lifecycle_state ? <p className="rounded-xl border border-[#d7e5df] bg-[#f9fcfa] px-4 py-3 text-sm font-semibold text-[#52736a]">{event.lifecycle_state === "upcoming" ? "Event has not started yet." : event.lifecycle_state === "ongoing" ? "Event is currently in progress." : "Event has ended."}</p> : null; }
function AttendanceVisual({ dashboard }: { dashboard: EventDashboard }) { const rate = dashboard.attendance.attendance_percentage ?? 0; return <DashboardPanel title="Registration / attendance"><div className="flex items-center gap-5"><div className="relative h-24 w-24 shrink-0 rounded-full" style={{ background: `conic-gradient(#1f6a58 ${rate}%, #e8efeb ${rate}% 100%)` }}><div className="absolute inset-3 flex items-center justify-center rounded-full bg-white text-sm font-bold text-[#06201c]">{formatNumber(rate)}%</div></div><div className="space-y-2 text-sm"><p><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#1f6a58]" />Checked in <strong>{dashboard.attendance.checked_in}</strong></p><p><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#d7e5df]" />Not checked in <strong>{dashboard.attendance.not_checked_in}</strong></p><p className="text-xs text-[#52736a]">Total registrations: {dashboard.registrations.total}</p></div></div></DashboardPanel>; }
function RegistrationStatusVisual({ dashboard }: { dashboard: EventDashboard }) { const values = [["Confirmed", dashboard.registrations.confirmed], ["Attended", dashboard.registrations.attended], ["Cancelled", dashboard.registrations.cancelled], ["No show", dashboard.registrations.no_show], ["Other", dashboard.registrations.other]] as const; return <DashboardPanel title="Registration status"><div className="space-y-3">{values.map(([status, count]) => <div key={status}><div className="flex justify-between text-sm"><StatusBadge value={status} /><strong className="text-[#06201c]">{count}</strong></div><div className="mt-1 h-2 rounded-full bg-[#edf3f0]"><div className="h-2 rounded-full bg-[#6cae88]" style={{ width: `${dashboard.registrations.total > 0 ? (count / dashboard.registrations.total) * 100 : 0}%` }} /></div></div>)}</div></DashboardPanel>; }
function RegistrationSummary({ dashboard, onViewAll }: { dashboard: EventDashboard; onViewAll: () => void }) { return <DashboardPanel title="Registrations"><div className="grid gap-3 sm:grid-cols-3"><SummaryItem label="Active" value={dashboard.registrations.active} /><SummaryItem label="Online" value={dashboard.registrations.online} /><SummaryItem label="Walk-in" value={dashboard.registrations.walk_in} /></div><button type="button" onClick={onViewAll} className="mt-4 text-sm font-semibold text-[#1f6a58] underline">View all registrations</button></DashboardPanel>; }
function SessionsSummary({ dashboard, timeZone, onViewDetails, enabled }: { dashboard: EventDashboard; timeZone: string; onViewDetails: () => void; enabled: boolean }) { if (!enabled) return null; return <DashboardPanel title="Sessions"><div className="flex items-start justify-between gap-3"><p className="text-sm text-[#52736a]">Backend attendance summary</p><button type="button" onClick={onViewDetails} className="text-sm font-semibold text-[#1f6a58] underline">View all</button></div>{dashboard.sessions.length === 0 ? <p className="mt-5 text-sm font-semibold text-[#52736a]">No sessions configured.</p> : <div className="mt-4 space-y-3">{dashboard.sessions.slice(0, 5).map((session) => <div key={session.session_id} className="rounded-xl border border-[#edf3f0] bg-[#f9fcfa] p-3"><p className="font-semibold text-[#06201c]">{session.title ?? "Session"}</p><p className="mt-1 text-sm text-[#52736a]">{formatSessionTime(session.session_date, session.start_time, timeZone)}</p><p className="mt-1 text-sm text-[#52736a]">{session.checked_in_count} of {session.registered_count} checked in{session.attendance_percentage !== null && session.attendance_percentage !== undefined ? ` · ${formatNumber(session.attendance_percentage)}%` : ""}</p></div>)}</div>}</DashboardPanel>; }
function CapacityVisual({ dashboard }: { dashboard: EventDashboard }) { const percentage = dashboard.capacity.fill_percentage; return <DashboardPanel title="Capacity"><p className="text-sm text-[#52736a]">{dashboard.capacity.unlimited ? "Unlimited capacity" : `${dashboard.capacity.seats_taken} seats taken${dashboard.capacity.seats_reserved > 0 ? ` · ${dashboard.capacity.seats_reserved} reserved` : ""}`}</p>{percentage !== null && percentage !== undefined ? <><div className="mt-3 h-3 rounded-full bg-[#edf3f0]"><div className="h-3 rounded-full bg-[#6cae88]" style={{ width: `${Math.min(100, Math.max(0, percentage))}%` }} /></div><p className="mt-2 text-xs font-semibold text-[#52736a]">{formatNumber(percentage)}% capacity used</p></> : null}</DashboardPanel>; }
function OrderSummary({ dashboard }: { dashboard: EventDashboard }) { return <DashboardPanel title="Revenue / orders"><div className="grid grid-cols-3 gap-3 text-sm"><div><p className="text-xs text-[#7f9d94]">Confirmed revenue</p><p className="mt-1 font-bold text-[#06201c]">{formatRevenue(dashboard.revenue)}</p></div><div><p className="text-xs text-[#7f9d94]">Orders</p><p className="mt-1 font-bold text-[#06201c]">{dashboard.orders.successful}</p></div><div><p className="text-xs text-[#7f9d94]">Pending</p><p className="mt-1 font-bold text-[#06201c]">{dashboard.orders.pending}</p></div></div></DashboardPanel>; }
function OptionSummary({ title, items }: { title: string; items: readonly { id: string; name: string; count: number; active: boolean; price?: number; currency?: string; capacity?: number | null; reserved?: number | null; remaining?: number | null; soldOut?: boolean }[] }) { return <DashboardPanel title={title}><div className="grid gap-3 sm:grid-cols-2">{items.map((item) => <div key={item.id} className="rounded-xl bg-[#f9fcfa] p-4"><div className="flex justify-between gap-3"><span className="font-semibold text-[#06201c]">{item.name}</span><strong className="text-[#1f6a58]">{item.count}</strong></div><p className="mt-1 text-xs text-[#52736a]">{item.price ?? "Not provided"} {item.currency ?? ""} · Capacity: {item.capacity ?? "Unlimited"}</p><p className="text-xs text-[#52736a]">{item.reserved !== null && item.reserved !== undefined ? `Reserved: ${item.reserved} · ` : ""}{item.remaining !== null && item.remaining !== undefined ? `Remaining: ${item.remaining} · ` : ""}{item.soldOut === undefined ? "Status unavailable" : item.soldOut ? "Sold out" : "Available"}</p>{!item.active ? <p className="mt-1 text-xs text-[#52736a]">Retired option</p> : null}</div>)}</div></DashboardPanel>; }
function SummaryItem({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-[#f9fcfa] p-4"><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#7f9d94]">{label}</p><p className="mt-1 text-xl font-bold text-[#06201c]">{value.toLocaleString()}</p></div>; }
function DashboardPanel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#e1ebe6] bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-[#06201c]">{title}</h2><div className="mt-4">{children}</div></section>; }
function StatusBadge({ value }: { value: string }) { return <span className="inline-flex rounded-full bg-[#e8f6ee] px-2.5 py-1 text-xs font-semibold capitalize text-[#1f6a58]">{value.replace(/[_-]+/g, " ")}</span>; }
function formatSessionTime(date: string | null | undefined, start: string | null | undefined, timeZone: string) { const parts = [date, start].filter(Boolean); return parts.length > 0 ? parts.join(" · ") : `Time unavailable (${timeZone})`; }
function formatNumber(value: number) { return Number.isInteger(value) ? value.toLocaleString() : value.toLocaleString(undefined, { maximumFractionDigits: 1 }); }
function formatPercentage(value: number | null, empty: string, suffix = "") { return value === null ? empty : `${formatNumber(value)}%${suffix}`; }
function formatRevenue(revenue: EventDashboard["revenue"]) { if (revenue.mixed_currency) return "Multiple currencies"; if (revenue.total_revenue === null) return "—"; if (!revenue.currency) return formatNumber(revenue.total_revenue); try { return new Intl.NumberFormat(undefined, { style: "currency", currency: revenue.currency, maximumFractionDigits: 2 }).format(revenue.total_revenue); } catch { return `${revenue.currency} ${formatNumber(revenue.total_revenue)}`; } }
