"use client";

import type { CreateEventFormValues } from "./create-event-form";

type Props = { values: CreateEventFormValues; update: <Key extends keyof CreateEventFormValues>(key: Key, value: CreateEventFormValues[Key]) => void };
export type EventServiceOption = { id?: string | null; name: string; description?: string | null; date?: string | null; active?: boolean; price?: string | null; currency?: string | null; capacity?: string | null; purchase_start_at?: string | null; purchase_end_at?: string | null; service_start_at?: string | null; service_end_at?: string | null };
type ServiceKind = "meals" | "accommodation";

function dateOnly(value: string): string { return value ? value.slice(0, 10) : ""; }
function scheduleText(start: string, end: string): string { return start && end ? `${start.replace("T", " ")} — ${end.replace("T", " ")}` : "Select the Event start and end time first."; }

export function EventServiceOptionEditor({ option, index, kind, enabled, currencyOptions, eventStart, eventEnd, onChange, onRemove }: { option: EventServiceOption; index: number; kind: ServiceKind; enabled: boolean; currencyOptions: readonly { value: string; label: string }[]; eventStart: string; eventEnd: string; onChange: (index: number, option: EventServiceOption) => void; onRemove: (index: number) => void }) {
  const update = (patch: Partial<EventServiceOption>) => onChange(index, { ...option, ...patch });
  const field = (label: string, key: keyof EventServiceOption, type = "text", bounds?: { min?: string; max?: string }) => <label className="block min-w-0 text-sm font-semibold">{label}<input type={type} min={bounds?.min} max={bounds?.max} disabled={!enabled} value={String(option[key] ?? "")} onChange={(event) => update({ [key]: event.target.value || null })} className="mt-1 h-10 w-full min-w-0 rounded-xl border border-[#d7e5df] px-3 disabled:bg-[#f4faf7]" /></label>;
  const serviceBounds = { min: eventStart || undefined, max: eventEnd || undefined };
  return <div className="grid min-w-0 gap-3 rounded-xl border border-[#edf3f0] p-3 md:grid-cols-2"><label className="block min-w-0 text-sm font-semibold">Name<input required disabled={!enabled} value={option.name} onChange={(event) => update({ name: event.target.value })} className="mt-1 h-10 w-full min-w-0 rounded-xl border border-[#d7e5df] px-3 disabled:bg-[#f4faf7]" /></label><label className="block min-w-0 text-sm font-semibold">Description<input disabled={!enabled} value={option.description ?? ""} onChange={(event) => update({ description: event.target.value })} className="mt-1 h-10 w-full min-w-0 rounded-xl border border-[#d7e5df] px-3 disabled:bg-[#f4faf7]" /></label>{kind === "meals" ? <label className="block min-w-0 text-sm font-semibold">Date<input type="date" min={dateOnly(eventStart) || undefined} max={dateOnly(eventEnd) || undefined} disabled={!enabled} value={option.date ?? ""} onChange={(event) => update({ date: event.target.value || null })} className="mt-1 h-10 w-full min-w-0 rounded-xl border border-[#d7e5df] px-3 disabled:bg-[#f4faf7]" /></label> : null}{field("Price", "price", "number")}{currencyOptions.length ? <label className="block min-w-0 text-sm font-semibold">Currency<select disabled={!enabled} value={option.currency ?? ""} onChange={(event) => update({ currency: event.target.value })} className="mt-1 h-10 w-full min-w-0 rounded-xl border border-[#d7e5df] px-3 disabled:bg-[#f4faf7]"><option value="">Select currency</option>{currencyOptions.map((currency) => <option key={currency.value} value={currency.value}>{currency.label}</option>)}</select></label> : field("Currency", "currency")}{field("Capacity", "capacity", "number")}{field("Available to buy from", "purchase_start_at", "datetime-local")}{field("Available to buy until", "purchase_end_at", "datetime-local")}{field("Service starts", "service_start_at", "datetime-local", serviceBounds)}{field("Service ends", "service_end_at", "datetime-local", { min: option.service_start_at || eventStart || undefined, max: eventEnd || undefined })}{kind === "accommodation" ? <div className="flex min-w-0 flex-wrap items-center gap-2 md:col-span-2"><button type="button" disabled={!enabled || !eventStart || !eventEnd} onClick={() => update({ service_start_at: eventStart || null, service_end_at: eventEnd || null })} className="h-9 self-start rounded-full border border-[#1f6a58] px-3 text-xs font-bold text-[#1f6a58] disabled:opacity-50">Use event schedule</button></div> : null}<label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" disabled={!enabled} checked={option.active !== false} onChange={(event) => update({ active: event.target.checked })} /> Active</label><button type="button" disabled={!enabled} onClick={() => onRemove(index)} className="justify-self-start text-sm font-bold text-[#b42318] disabled:opacity-50">Remove</button></div>;
}

export function EventServiceOptionsEditor({ kind, title, options, enabled, currencyOptions = [], eventStart, eventEnd, onAdd, onChange, onRemove }: { kind: ServiceKind; title: string; options: readonly EventServiceOption[]; enabled: boolean; currencyOptions?: readonly { value: string; label: string }[]; eventStart: string; eventEnd: string; onAdd: () => void; onChange: (index: number, option: EventServiceOption) => void; onRemove: (index: number) => void }) {
  if (!enabled && options.length === 0) return null;
  return <section className="mt-6 rounded-2xl border border-[#d7e5df] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-[#06201c]">{title}</h2>{!enabled ? <p className="mt-1 text-xs font-semibold text-[#52736a]">{title} is disabled for this Event Type. Existing values are preserved.</p> : null}</div><button type="button" disabled={!enabled} onClick={onAdd} className="rounded-full border border-[#1f6a58] px-3 py-1 text-sm font-bold text-[#1f6a58] disabled:opacity-50">Add option</button></div><p className="mt-2 rounded-lg bg-[#f4faf7] px-3 py-2 text-xs text-[#52736a]"><strong>Event schedule:</strong> {scheduleText(eventStart, eventEnd)}</p><div className="mt-4 space-y-3">{options.map((option, index) => <EventServiceOptionEditor key={option.id ?? index} option={option} index={index} kind={kind} enabled={enabled} currencyOptions={currencyOptions} eventStart={eventStart} eventEnd={eventEnd} onChange={onChange} onRemove={onRemove} />)}</div></section>;
}

export default function EventServicesEditor({ values, update, currencyOptions = [] }: Props & { currencyOptions?: readonly { value: string; label: string }[] }) {
  const meals = values.meals ?? { options: [] };
  const accommodation = values.accommodation ?? { options: [] };
  const updateOptions = (key: ServiceKind, options: EventServiceOption[]) => update(key, (key === "meals" ? { ...meals, options } : { ...accommodation, options }) as CreateEventFormValues[typeof key]);
  const section = (key: ServiceKind, title: string, options: readonly EventServiceOption[]) => values.modules?.[key] === true ? <EventServiceOptionsEditor kind={key} title={title} options={options} enabled currencyOptions={currencyOptions} eventStart={values.start_date} eventEnd={values.end_date} onAdd={() => updateOptions(key, [...options, { name: "", description: "", ...(key === "meals" ? { date: "" } : {}) }])} onChange={(index, option) => updateOptions(key, options.map((item, itemIndex) => itemIndex === index ? option : item))} onRemove={(index) => updateOptions(key, options.filter((_, itemIndex) => itemIndex !== index))} /> : null;
  return <>{section("meals", "Meals", meals.options ?? [])}{section("accommodation", "Accommodation", accommodation.options ?? [])}</>;
}
