"use client";

import { useState } from "react";
import type { WorkflowAdminCapabilities } from "./types";
import { useWorkflow, useWorkflowForms, useWorkflowMutations, useWorkflowVersion, useWorkflowVersions, useWorkflows } from "./hooks";
import { ApiDebugPanel } from "./components/ApiDebugPanel";
import { WorkflowEditor } from "./components/WorkflowEditor";
import { WorkflowLibrary } from "./components/WorkflowLibrary";
import { WorkflowVersions } from "./components/WorkflowVersions";
import { WorkspaceCard, WorkspaceError, WorkspaceSkeleton } from "./components/WorkspacePrimitives";

/** Renders the reusable Workflow library, canonical composer, and read-only version history. */
export function WorkflowsWorkspace({ capabilities }: { capabilities: WorkflowAdminCapabilities }) {
  const [selectedWorkflowId, setSelectedWorkflowId] = useState<string | null>(null); const [selectedVersion, setSelectedVersion] = useState<number | null>(null);
  const workflowsQuery = useWorkflows(); const formsQuery = useWorkflowForms({ publishedOnly: true }); const workflowQuery = useWorkflow(selectedWorkflowId); const versionsQuery = useWorkflowVersions(selectedWorkflowId); const versionQuery = useWorkflowVersion(selectedWorkflowId, selectedVersion); const mutations = useWorkflowMutations();
  const selectedWorkflow = workflowQuery.data?.data ?? null; const availableForms = formsQuery.data?.data ?? [];
  const isMutating = mutations.create.isPending || mutations.update.isPending || mutations.publish.isPending || mutations.remove.isPending; const mutationError = [mutations.create.error, mutations.update.error, mutations.publish.error, mutations.remove.error].find(Boolean);
  const selectWorkflow = (workflowId: string) => { setSelectedWorkflowId(workflowId); setSelectedVersion(null); };
  const refreshSelection = async (workflowId: string) => { selectWorkflow(workflowId); await workflowsQuery.refetch(); await workflowQuery.refetch(); };
  return <div className="mx-auto w-full max-w-[1500px] space-y-5"><header><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#7f9d94]">Temporary integration workspace</p><h1 className="mt-1 text-2xl font-bold text-[#06201c]">Workflow Lab</h1><p className="mt-1 text-sm text-[#52736a]">Reusable workflow composition hosted temporarily in Enterprise Admin.</p></header>{mutationError ? <div role="alert" className="rounded-xl border border-[#f3c8c2] bg-[#fff5f4] p-3 text-sm text-[#b42318]">{mutationError instanceof Error ? mutationError.message : "Workflow request failed."}</div> : null}<div className="grid gap-5 xl:grid-cols-[280px_minmax(0,1fr)_320px]"><WorkspaceCard title="Workflow library" actions={<button type="button" onClick={() => void workflowsQuery.refetch()} className="text-xs font-semibold text-[#1f6a58]">Refresh</button>}><WorkflowLibrary workflows={workflowsQuery.data?.data ?? []} selectedWorkflowId={selectedWorkflowId} isLoading={workflowsQuery.isPending} error={workflowsQuery.error} onSelect={selectWorkflow} onRetry={() => void workflowsQuery.refetch()} /></WorkspaceCard><div className="space-y-5">{selectedWorkflowId && workflowQuery.isPending ? <WorkspaceSkeleton /> : workflowQuery.error ? <WorkspaceError error={workflowQuery.error} onRetry={() => void workflowQuery.refetch()} /> : <WorkflowEditor workflow={selectedWorkflow} capabilities={capabilities} forms={availableForms} isSaving={isMutating} onCreate={(input) => mutations.create.mutate(input, { onSuccess: (result) => void refreshSelection(result.data.id) })} onSave={(input) => selectedWorkflow && mutations.update.mutate({ workflowId: selectedWorkflow.id, input }, { onSuccess: () => void workflowQuery.refetch() })} onPublish={(input) => { if (selectedWorkflow && window.confirm(`Publish ${input.name}?`)) mutations.publish.mutate({ workflowId: selectedWorkflow.id, input }, { onSuccess: () => void refreshSelection(selectedWorkflow.id) }); }} onDelete={() => { if (selectedWorkflow && window.confirm(`Delete ${selectedWorkflow.name}? This action cannot be undone from this workspace.`)) mutations.remove.mutate(selectedWorkflow.id, { onSuccess: () => { setSelectedWorkflowId(null); void workflowsQuery.refetch(); } }); }} />}{formsQuery.error ? <WorkspaceError error={formsQuery.error} onRetry={() => void formsQuery.refetch()} /> : null}<ApiDebugPanel /></div><div className="space-y-5"><WorkflowVersions versions={versionsQuery.data?.data ?? []} selectedVersion={selectedVersion} detail={versionQuery.data?.data ?? null} isLoading={versionsQuery.isPending || versionQuery.isPending} error={versionsQuery.error ?? versionQuery.error} onSelect={setSelectedVersion} onRetry={() => void versionsQuery.refetch()} /><WorkspaceCard title="Composer contract"><p className="text-sm text-[#52736a]">The visual composer writes a linear <code>start</code> to <code>form_ref</code> graph. Advanced graphs remain editable only as Raw JSON.</p></WorkspaceCard></div></div></div>;
}
