"use client";

import type { WorkflowFormDefinition } from "@ihp/workflow-runtime";
import { WorkspaceCard } from "./WorkspacePrimitives";

/** Renders a non-submitting preview for documented Form field types. */
export function FormPreview({ definition }: { definition: WorkflowFormDefinition }) {
  return <WorkspaceCard title="Form preview"><p className="text-sm text-[#52736a]">Preview only — this does not submit or create a workflow session.</p><div className="mt-4 space-y-4"><h3 className="text-lg font-bold text-[#06201c]">{definition.title}</h3>{definition.fields.map((field) => <label key={field.id} className="block text-sm font-semibold text-[#16332b]">{field.label}{field.required ? <span className="ml-1 text-[#b42318]">*</span> : null}{field.type === "textarea" ? <textarea disabled className="mt-1 min-h-20 w-full rounded-xl border border-[#d7e5df] bg-[#f9fcfa] p-3" /> : field.type === "radio" ? <span className="mt-2 block space-y-1">{field.options.map((option) => <span key={option} className="flex items-center gap-2 font-normal"><input type="radio" disabled name={field.id} />{option}</span>)}</span> : field.type === "dropdown" ? <select disabled className="mt-1 h-10 w-full rounded-xl border border-[#d7e5df] bg-[#f9fcfa] px-3"><option>Select an option</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : field.type === "multiselect" ? <span className="mt-2 block space-y-1">{field.options.map((option) => <span key={option} className="flex items-center gap-2 font-normal"><input type="checkbox" disabled />{option}</span>)}</span> : ["photo", "signature", "audio", "video", "file"].includes(field.type) ? <span className="mt-1 flex h-10 items-center rounded-xl border border-dashed border-[#bcd8cd] bg-[#f9fcfa] px-3 text-xs font-normal text-[#52736a]">{field.type} upload placeholder</span> : <input disabled type={field.type} className="mt-1 h-10 w-full rounded-xl border border-[#d7e5df] bg-[#f9fcfa] px-3" />}</label>)}</div></WorkspaceCard>;
}
