"use client";

import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { createWorkflowFormField, isChoiceFieldType, reorderWorkflowFormFields, supportedFormFieldTypes, updateWorkflowFormField, type WorkflowFormDefinition, type WorkflowFormDefinitionField } from "@ihp/workflow-runtime";

function SortableField({ field, index, onChange, onDelete, onDuplicate }: { field: WorkflowFormDefinitionField; index: number; onChange: (field: WorkflowFormDefinitionField) => void; onDelete: () => void; onDuplicate: () => void }) {
  const sortable = useSortable({ id: field.id }); const { attributes, listeners, setNodeRef, transform, transition } = sortable;
  const style = { transform: CSS.Transform.toString(transform), transition };
  const changeOption = (optionIndex: number, value: string) => onChange(updateWorkflowFormField(field, { options: field.options.map((option, currentIndex) => currentIndex === optionIndex ? value : option) }));
  return <article ref={setNodeRef} style={style} className="rounded-xl border border-[#e1ebe6] bg-[#fbfdfc] p-3"><div className="flex items-center justify-between gap-2"><button type="button" {...attributes} {...listeners} className="cursor-grab rounded px-2 py-1 text-xs font-bold text-[#52736a]" aria-label={`Reorder ${field.label || `field ${index + 1}`}`}>↕</button><span className="min-w-0 flex-1 truncate text-sm font-bold text-[#16332b]">Field {index + 1}</span><details className="text-xs text-[#52736a]"><summary className="cursor-pointer">Advanced</summary><p className="mt-1 break-all font-mono">{field.id}</p></details></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-[#16332b]">Label<input value={field.label} onChange={(event) => onChange(updateWorkflowFormField(field, { label: event.target.value }))} className="mt-1 h-9 w-full rounded-lg border border-[#d7e5df] px-2 text-sm" /></label><label className="text-sm font-semibold text-[#16332b]">Type<select value={field.type} onChange={(event) => onChange(updateWorkflowFormField(field, { type: event.target.value as WorkflowFormDefinitionField["type"] }))} className="mt-1 h-9 w-full rounded-lg border border-[#d7e5df] px-2 text-sm">{supportedFormFieldTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></label></div><label className="mt-3 flex items-center gap-2 text-sm font-semibold text-[#16332b]"><input type="checkbox" checked={field.required} onChange={(event) => onChange(updateWorkflowFormField(field, { required: event.target.checked }))} />Required</label>{isChoiceFieldType(field.type) ? <div className="mt-3 rounded-lg border border-[#e7efeb] bg-white p-3"><p className="text-sm font-semibold text-[#16332b]">Options</p>{field.options.map((option, optionIndex) => <div key={`${field.id}-${optionIndex}`} className="mt-2 flex gap-2"><input value={option} onChange={(event) => changeOption(optionIndex, event.target.value)} className="h-9 min-w-0 flex-1 rounded-lg border border-[#d7e5df] px-2 text-sm" aria-label={`Option ${optionIndex + 1}`} /><button type="button" onClick={() => onChange(updateWorkflowFormField(field, { options: field.options.filter((_, currentIndex) => currentIndex !== optionIndex) }))} className="text-sm font-semibold text-[#b42318]">Delete</button></div>)}<button type="button" onClick={() => onChange(updateWorkflowFormField(field, { options: [...field.options, ""] }))} className="mt-2 text-sm font-semibold text-[#1f6a58]">+ Add Option</button></div> : null}<div className="mt-3 flex gap-3"><button type="button" onClick={onDuplicate} className="text-sm font-semibold text-[#1f6a58]">Duplicate</button><button type="button" onClick={onDelete} className="text-sm font-semibold text-[#b42318]">Delete</button></div></article>;
}

/** Schema-aware visual builder for the documented Forms definition structure. */
export function FormBuilder({ definition, onChange }: { definition: WorkflowFormDefinition; onChange: (definition: WorkflowFormDefinition) => void }) {
  const sensors = useSensors(useSensor(PointerSensor), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  const updateField = (index: number, field: WorkflowFormDefinitionField) => onChange({ ...definition, fields: definition.fields.map((current, currentIndex) => currentIndex === index ? field : current) });
  const addField = (type: WorkflowFormDefinitionField["type"]) => {
    const field = updateWorkflowFormField(createWorkflowFormField(), { type });
    onChange({ ...definition, fields: [...definition.fields, field] });
  };
  const onDragEnd = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; const fromIndex = definition.fields.findIndex((field) => field.id === active.id); const toIndex = definition.fields.findIndex((field) => field.id === over.id); onChange({ ...definition, fields: reorderWorkflowFormFields(definition.fields, fromIndex, toIndex) }); };
  return <div className="space-y-4"><label className="block text-sm font-semibold text-[#16332b]">Definition Title<input value={definition.title} onChange={(event) => onChange({ ...definition, title: event.target.value })} className="mt-1 h-10 w-full rounded-xl border border-[#d7e5df] px-3 outline-none focus:border-[#1f6a58]" /></label><div><p className="text-sm font-semibold text-[#16332b]">Field palette</p><div className="mt-2 flex flex-wrap gap-2">{supportedFormFieldTypes.map((type) => <button key={type} type="button" onClick={() => addField(type)} className="rounded-full border border-[#1f6a58] px-3 py-1.5 text-xs font-semibold text-[#1f6a58]">+ {type}</button>)}</div></div><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}><SortableContext items={definition.fields.map((field) => field.id)} strategy={verticalListSortingStrategy}><div className="space-y-3">{definition.fields.map((field, index) => <SortableField key={field.id} field={field} index={index} onChange={(nextField) => updateField(index, nextField)} onDelete={() => onChange({ ...definition, fields: definition.fields.filter((_, currentIndex) => currentIndex !== index) })} onDuplicate={() => { const duplicate = { ...field, id: createWorkflowFormField().id, label: `${field.label} copy`, options: [...field.options] }; onChange({ ...definition, fields: [...definition.fields.slice(0, index + 1), duplicate, ...definition.fields.slice(index + 1)] }); }} />)}</div></SortableContext></DndContext>{definition.fields.length === 0 ? <p className="rounded-xl border border-dashed border-[#d7e5df] p-5 text-center text-sm text-[#52736a]">Add a field to begin building this Form.</p> : null}</div>;
}
