export type ProductDto = {
  id: string;
  enterprise_id: string;
  location_id?: string | null;
  product_name: string;
  product_description: string;
  product_category: string;
  product_price: number;
  product_images: string;
  product_status: boolean;
  sku?: string;
  barcode_upc?: string;
  weight?: number;
  dimensions?: string;
  sale_price?: number;
  cost_price?: number;
  tax_class?: string;
  stock_quantity?: number;
  low_stock_alert_threshold?: number;
  stock_management?: string;
  currency?: string;
  publish_status?: string;
};

export type CreateProductPayload = {
  enterprise_id: string;
  location_id?: string;
  product_name: string;
  product_description: string;
  product_category: string;
  product_price: number;
  product_images: string;
  product_status: boolean;
  sku?: string;
  barcode_upc?: string;
  weight?: number;
  dimensions?: string;
  sale_price?: number;
  cost_price?: number;
  tax_class?: string;
  stock_quantity?: number;
  low_stock_alert_threshold?: number;
  stock_management?: string;
  currency?: string;
  publish_status?: string;
};

export type UpdateProductPayload = Partial<{
  enterprise_id: string;
  location_id: string;
  product_name: string;
  product_description: string;
  product_category: string;
  product_price: number;
  product_images: string;
  product_status: boolean;
  sku: string;
  barcode_upc: string;
  weight: number;
  dimensions: string;
  sale_price: number;
  cost_price: number;
  tax_class: string;
  stock_quantity: number;
  low_stock_alert_threshold: number;
  stock_management: string;
  currency: string;
  publish_status: string;
}>;

export type ProductListItem = {
  id: string;
  enterpriseId: string;
  name: string;
  description: string;
  category: string;
  price: string;
  image: string;
  status: "Active" | "Inactive";
  enterprise: string;
  stock: string;
  sales: string;
};
