/** Temporary centralized UI copy under ADR-002; migrate to shared i18n when available. */
export const formConfigurationCopy = {
  eyebrow: "SUPER ADMIN · CONFIGURATION",
  title: "Form Configurations",
  description: "Configure reusable form experiences for platform modules.",
  create: "+ Create Configuration",
  createTitle: "Create Form Configuration",
  editTitle: "Edit Form Configuration",
  viewTitle: "Form Configuration",
  type: "Type", name: "Name", descriptionLabel: "Description", scope: "Scope", status: "Status", active: "Active", version: "Version", assignedTenants: "Assigned Tenants", updatedAt: "Updated At", actions: "Actions",
  event: "Event", global: "Global", selective: "Selective Tenants", draft: "Draft", published: "Published", retired: "Retired", activeLabel: "Active", inactive: "Inactive",
  basics: "Configuration details", builder: "Form builder", assignment: "Assignment", preview: "Preview as Enterprise Admin",
  configurationName: "Configuration name", configurationType: "Configuration type", addSection: "Add section", addField: "+ Add field", addCoreField: "Add core field", addCustomField: "Add custom field", saveDraft: "Save Draft", publish: "Publish", activate: "Activate", deactivate: "Deactivate", retire: "Retire", duplicate: "Duplicate", duplicateSection: "Duplicate section", viewVersions: "View Versions", audit: "Audit", edit: "Edit", view: "View", delete: "Delete configuration", moreActions: "More actions", moveUp: "Move section up", moveDown: "Move section down", rename: "Rename", sectionDescription: "Section description", enabled: "Enabled", disabled: "Disabled", reviewSubmit: "Review & Submit", systemStep: "System-controlled final step", formStructure: "Form structure", settings: "Field / Section settings", openSettings: "Open settings", closeSettings: "Close settings", builderTab: "Builder", previewTab: "Preview", fieldCount: "{count} fields", sectionNumber: "{number}.", optional: "Optional", coreKey: "Core key", rendererLocked: "Renderer locked", coreKeyLocked: "Core key cannot be changed", editSection: "Edit section", searchCoreFields: "Search core fields", chooseFieldSource: "Choose a field source", noCoreFields: "No available core fields", createCustomField: "Create custom field", add: "Add", cancel: "Cancel", selectItem: "Select a section or field to edit its settings.",
  label: "Label", renderer: "Renderer", semanticRenderer: "Semantic renderer", taxonomySelect: "Registry-backed select", taxonomyOptionsAtRuntime: "Options load from the field's configured backend source.", placeholder: "Placeholder", helpText: "Help text", options: "Options", validation: "Validation", validationIntro: "Control how much text users can enter. All settings are optional unless required by the Event domain.", minLength: "Minimum characters", maxLength: "Maximum characters", minimum: "Minimum", maximum: "Maximum", pattern: "Format rule", advancedValidation: "Advanced validation", patternHelp: "Optional. Use this only when the text must follow a specific format. Most fields do not need this setting.", patternNote: "This is an advanced regular-expression rule.", minLengthHelp: "The fewest number of characters a user must enter. Leave empty if there is no minimum.", maxLengthHelp: "The maximum number of characters a user can enter. Leave empty if there is no limit.", optionLabel: "Option label", optionValue: "Option value", addOption: "Add option", newOption: "New option", required: "Required", position: "Position", section: "Section", fieldSource: "Field source", core: "Core", custom: "Custom", immutable: "Core key is immutable", cannotRemoveFromForm: "This core field cannot be removed from this form.", removeFromForm: "Remove from form", domainRequired: "Required by Event domain", customField: "Custom field", noFields: "No fields have been added to this section.",
  allTenants: "All tenants", selectedTenants: "Selected tenants", searchTenants: "Search tenants", selectAll: "Select all", clearAll: "Clear all", selectedCount: "Selected tenants: {count}", noTenants: "No tenants match this search.", noTenantsAssigned: "No tenants assigned.", assignmentDescription: "Choose who can use this configuration.", selectedTenantsSavedOnCreate: "Selected tenants will be saved when this configuration is created.", loadingAssignedTenants: "Loading assigned tenants…", unableToLoadAvailableTenants: "Unable to load available tenants.", unableToLoadAssignedTenants: "Unable to load assigned tenants.", globalAssignmentsDescription: "Global configurations resolve for all tenants; no assignments are sent.", saveAssignments: "Save assignments", savingAssignments: "Saving assignments...", selectiveTenantRequiredBeforeSave: "Select at least one tenant before saving this selective configuration.",
  previewDescription: "This preview uses configuration state only and does not submit an Event.", emptyConfigurations: "No form configurations yet.", validationName: "Enter a configuration name before saving.", confirmDelete: "Delete this section? Fields in the section will be removed from this mock configuration.",
  loading: "Loading…", retry: "Retry", loadError: "Unable to load this data. Please try again.", unauthorized: "You are not authorized to view this configuration data.", forbidden: "Your account does not have access to this configuration data.", emptyFieldRegistry: "No core fields are available from the platform registry.", unavailableFieldRegistry: "The field registry must load before fields can be configured.", notAvailable: "—",
  versionPrefix: "v", mock: { defaultName: "Default Event Form", defaultDescription: "Default configuration for Event creation.", healthcareName: "Healthcare Event Form", healthcareDescription: "A tenant-selective Event configuration.", tenants: { aurora: "Aurora Health", wellness: "Wellness Collective", horizon: "Horizon Care", vital: "Vital Partners" } },
  fieldTypes: { text: "Text", textarea: "Textarea", number: "Number", url: "URL", date: "Date", datetime: "Datetime", select: "Select", multi_select: "Multi Select", checkbox: "Checkbox" },
  seededSections: { basic: "Basic Information", schedule: "Schedule", location: "Location & Host", pricing: "Pricing & Tickets", capacity: "Capacity & Registration", media: "Images & Media", additional: "Additional Configuration" },
  coreFields: { title: "Title", description: "Description", category: "Category", subcategory: "Subcategory", tags: "Tags", organiser_name: "Organiser name", organiser_contact: "Organiser contact", start_date: "Start date", end_date: "End date", time_zone: "Time zone", registration_open_at: "Registration opens", registration_close_at: "Registration closes", registration_cutoff: "Registration cutoff", location_id: "Location", delivery_mode: "Delivery mode", "venue.name": "Venue name", "venue.address": "Venue address", "venue.city": "Venue city", "venue.coordinates.lat": "Venue latitude", "venue.coordinates.lng": "Venue longitude", meeting_link: "Meeting link", meeting_provider: "Meeting provider", price: "Price", currency: "Currency", capacity: "Capacity", min_participants: "Minimum participants", max_participants: "Maximum participants", primary_image: "Primary image", gallery_images: "Gallery images", videos: "Videos", documents: "Documents", ticket_types: "Ticket types", sessions: "Sessions", custom_fields: "Registration questions" },
  valueType: "Value type", builderHelp: "Click a field or section to edit it in the panel on the right. Drag items to reorder or move them between sections.", viewTips: "View tips", hideTips: "Hide tips", tipDragSections: "Drag sections to reorder the form.", tipDragFields: "Drag fields to reorder them or move them into another section.", tipAddField: "Use + Add field inside a section to add more fields.", tipAddSection: "To add a new section, scroll to the bottom of the builder and select Add section.", tipLocked: "Some Core field settings may be locked to protect Event requirements.", tipPreview: "Use Preview to review how the form will appear before publishing.", emptySection: "No fields yet. Add a field below or drag one here from another section.", addFieldHelp: "Add a core Event field or create a custom field.", addSectionHelp: "Need another group of fields? Add a section here.",
} as const;

export const formConfigurationManagementCopy = {
  appliesToAllTenants: "Applies to all tenants",
  assignedTenants: "Assigned tenants",
  assignedTenantsCount: (count: number) => `${count} tenants`,
  searchTenants: "Search tenants...",
  lifecycleNoticeTitle: "About form configuration lifecycle",
  lifecycleNoticeDescription: "Configurations already referenced by Events are retained for historical consistency and should be retired instead of deleted.",
} as const;
