"use client";

import { useMemo, useState } from "react";
import { formConfigurationCopy as copy } from "../constants/form-configuration-copy";
import type { FormConfigurationScope } from "../model/form-configuration.types";

export interface AssignmentTenantOption { id: string; name: string; slug: string | null; assignmentTenantId?: string | null; }
type Props = { readOnly?: boolean; scope: FormConfigurationScope; tenantIds: string[]; tenants: readonly AssignmentTenantOption[]; isLoadingTenants: boolean; tenantError: boolean; isLoadingAssignments?: boolean; assignmentError?: boolean; isPersisted: boolean; canSaveAssignments: boolean; isSaving: boolean; onScopeChange: (scope: FormConfigurationScope) => void; onTenantIdsChange: (ids: string[]) => void; onSave: () => void; };

/** Edits backend-owned tenant assignments without inventing tenant identities. */
export function AssignmentEditor({ scope, tenantIds, tenants, isLoadingTenants, tenantError, isLoadingAssignments = false, assignmentError = false, isPersisted, canSaveAssignments, readOnly = !canSaveAssignments, isSaving, onScopeChange, onTenantIdsChange, onSave }: Props) {
  const [search, setSearch] = useState("");
  const filtered = useMemo(() => tenants.filter((tenant) => tenant.name.toLowerCase().includes(search.toLowerCase())), [search, tenants]);
  const toggle = (tenantId: string) => onTenantIdsChange(tenantIds.includes(tenantId) ? tenantIds.filter((id) => id !== tenantId) : [...tenantIds, tenantId]);
  const tenantControls = <>{isLoadingTenants ? <p>{copy.loading}</p> : null}{tenantError ? <p role="alert">Unable to load available tenants.</p> : null}{!isLoadingTenants && !tenantError ? <><input disabled={readOnly} value={search} onChange={(event) => setSearch(event.target.value)} placeholder={copy.searchTenants} aria-label={copy.searchTenants} /><div><button type="button" disabled={readOnly} onClick={() => onTenantIdsChange(tenants.flatMap((tenant) => tenant.assignmentTenantId ? [tenant.assignmentTenantId] : []))}>{copy.selectAll}</button><button type="button" disabled={readOnly} onClick={() => onTenantIdsChange([])}>{copy.clearAll}</button></div>{filtered.map((tenant) => <label key={tenant.id}><input type="checkbox" checked={Boolean(tenant.assignmentTenantId && tenantIds.includes(tenant.assignmentTenantId))} disabled={readOnly || !tenant.assignmentTenantId} onChange={() => tenant.assignmentTenantId && toggle(tenant.assignmentTenantId)} />{tenant.name}</label>)}</> : null}</>;
  return <section className="rounded-2xl border border-[#dfe9e4] bg-white p-4"><h3>{copy.assignment}</h3><label><input type="radio" disabled={readOnly} checked={scope === "global"} onChange={() => onScopeChange("global")} />{copy.allTenants}</label><label><input type="radio" disabled={readOnly} checked={scope === "selective"} onChange={() => onScopeChange("selective")} />{copy.selectedTenants}</label>{scope === "selective" ? <div><p>{copy.selectedCount.replace("{count}", String(tenantIds.length))}</p>{!tenantIds.length && !isLoadingAssignments && !assignmentError ? <p>No tenants assigned.</p> : null}{!isPersisted ? <p>Save this configuration before assigning tenants.</p> : null}{isLoadingAssignments ? <p>Loading assigned tenants…</p> : null}{assignmentError ? <p role="alert">Unable to load assigned tenants.</p> : null}{tenantControls}</div> : <p>Global configurations resolve for all tenants; no assignments are sent.</p>}{!readOnly && isPersisted && canSaveAssignments && scope === "selective" ? <button type="button" onClick={onSave} disabled={isSaving || isLoadingTenants || tenantError || isLoadingAssignments || assignmentError}>{isSaving ? "Saving assignments..." : "Save assignments"}</button> : null}</section>;
}
