"use client";

import { useState } from "react";
import { useEventFormConfigurationAudit, useEventFormConfigurationVersion, useEventFormConfigurationVersions } from "../form-configurations.queries";
import { toBuilderFormConfiguration } from "../model/form-configuration.mappers";
import type { EventFormConfiguration } from "../model/event-form-configuration-api.types";
import { ConfigurationPreview } from "./ConfigurationPreview";

/** Displays immutable version and audit data for a persisted configuration. */
export function ConfigurationHistoryPanels({ configuration }: { configuration: EventFormConfiguration }) {
  const [selectedVersionId, setSelectedVersionId] = useState<string>();
  const versions = useEventFormConfigurationVersions(configuration.id);
  const version = useEventFormConfigurationVersion(configuration.id, selectedVersionId);
  const audit = useEventFormConfigurationAudit(configuration.id);
  return <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-[#dfe9e4] bg-white p-5"><h2 className="text-lg font-bold text-[#06201c]">Versions</h2>{versions.isLoading ? <p className="mt-3 text-sm text-[#52736a]">Loading versions…</p> : versions.isError ? <button type="button" onClick={() => void versions.refetch()} className="mt-3 text-sm font-semibold text-[#1f6a58]">Unable to load versions. Retry</button> : <div className="mt-3 space-y-2">{versions.data?.length ? versions.data.map((item) => <button key={item.id} type="button" onClick={() => setSelectedVersionId(item.id)} className="block w-full rounded-xl border border-[#edf3f0] p-3 text-left text-sm hover:bg-[#f4faf7]"><span className="font-bold text-[#06201c]">v{item.version}</span><span className="ml-2 text-[#52736a]">{item.status}</span><span className="mt-1 block text-xs text-[#52736a]">Created {item.created_at ?? "—"}{item.published_at ? ` · Published ${item.published_at}` : ""}</span></button>) : <p className="text-sm text-[#52736a]">No versions have been published.</p>}</div>}{selectedVersionId ? <div className="mt-4">{version.isLoading ? <p className="text-sm text-[#52736a]">Loading version…</p> : version.data ? <ConfigurationPreview configuration={toBuilderFormConfiguration(configuration, version.data)} /> : null}</div> : null}</section><section className="rounded-2xl border border-[#dfe9e4] bg-white p-5"><h2 className="text-lg font-bold text-[#06201c]">Audit history</h2>{audit.isLoading ? <p className="mt-3 text-sm text-[#52736a]">Loading audit history…</p> : audit.isError ? <div className="mt-3"><p role="alert" className="text-sm font-semibold text-[#b42318]">{audit.error instanceof Error ? audit.error.message : "Unable to load audit history."}</p><button type="button" onClick={() => void audit.refetch()} className="mt-2 text-sm font-semibold text-[#1f6a58]">Retry</button></div> : <div className="mt-3 space-y-3">{audit.data?.length ? audit.data.map((entry) => <article key={entry.id} className="border-l-2 border-[#cfe0d8] pl-3"><p className="text-sm font-bold text-[#06201c]">{entry.action}</p><p className="text-xs text-[#52736a]">{entry.actor_id ?? "System"} · {entry.created_at}</p></article>) : <p className="text-sm text-[#52736a]">No audit history is available.</p>}</div>}</section></div>;
}
