"use client";

import { formConfigurationCopy as copy } from "../constants/form-configuration-copy";
import { useState } from "react";
import { getEventCompositeFieldDefinition } from "../model/event-composite-field-definitions";
import { getEventCoreFieldSemantic, isEventCoreFieldRuntimeSourced } from "../model/event-core-field-semantics";
import { normalizeOptionPositions } from "../model/form-configuration-ordering";
import type { ConfiguredField, CoreFieldRegistryItem, FormFieldOption, FormFieldValidation, FormRenderer } from "../model/form-configuration.types";
import { CompositeFieldEditor } from "./CompositeFieldEditor";

const renderers = Object.keys(copy.fieldTypes) as FormRenderer[];

/** Edits a selected field while preserving registry and taxonomy constraints. */
export function FieldEditor({ field, registry, validationErrors = [], onChange, onRemoveFromForm }: { field: ConfiguredField; registry: readonly CoreFieldRegistryItem[]; validationErrors?: readonly string[]; onChange: (patch: Partial<ConfiguredField>) => void; onRemoveFromForm: () => void }) {
  const core = field.coreKey ? registry.find((item) => item.key === field.coreKey) : undefined;
  const taxonomySemantic = field.source === "core" ? getEventCoreFieldSemantic(field.coreKey) : undefined;
  const runtimeSourced = field.source === "core" && isEventCoreFieldRuntimeSourced(field.coreKey);
  const compositeDefinition = field.source === "core" ? getEventCompositeFieldDefinition(field.coreKey) : undefined;
  const allowedRenderers = core?.allowedRenderers ?? renderers;
  const rendererCanChange = !runtimeSourced && (!core || (core.configurable.renderer && core.allowedRenderers.length > 1));
  const canRemoveFromForm = field.source === "custom" || !core || core.removable;
  const textValidation = field.valueType === "string" && !runtimeSourced;
  const numberValidation = field.valueType === "number";
  const updateOption = (index: number, patch: Partial<FormFieldOption>) => onChange({ options: normalizeOptionPositions(field.options.map((option, optionIndex) => optionIndex === index ? { ...option, ...patch } : option)) });
  const moveOption = (index: number, amount: number) => { const target = index + amount; if (target < 0 || target >= field.options.length) return; const options = [...field.options]; [options[index], options[target]] = [options[target], options[index]]; onChange({ options: normalizeOptionPositions(options) }); };
  const setValidation = (patch: Partial<FormFieldValidation>) => onChange({ validation: { ...field.validation, ...patch } });

  return <article className="min-w-0 max-w-full rounded-xl border border-[#dfe9e4] bg-white p-4"><style>{`article fieldset > div > div { min-width: 0; grid-template-columns: minmax(0, 1fr); } @media (min-width: 640px) { article fieldset > div > div { grid-template-columns: minmax(0, 1fr) minmax(0, 1fr) auto; } } article fieldset > div > div > input { min-width: 0; width: 100%; } article fieldset > div > div > span { display: flex; flex-wrap: wrap; } article button[aria-label="Delete"] { font-size: 0; } article button[aria-label="Delete"]::after { content: "Remove"; font-size: 0.875rem; }`}</style>
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="font-bold text-[#06201c]">{field.label} <span className="ml-2 rounded-full bg-[#eef6f2] px-2 py-0.5 text-xs text-[#1f6a58]">{field.source === "core" ? copy.core : copy.custom}</span></p>{canRemoveFromForm ? <button type="button" onClick={onRemoveFromForm} className="text-sm font-semibold text-[#b42318]">{copy.removeFromForm}</button> : <span className="text-xs text-[#52736a]">{copy.cannotRemoveFromForm}</span>}</div>
    {validationErrors.length ? <div role="alert" className="mt-3 rounded-lg border border-[#f0c8c4] bg-[#fff8f7] p-3 text-sm font-semibold text-[#b42318]">{validationErrors.map((message) => <p key={message}>{message}</p>)}</div> : null}
    {core ? <div className="mt-3 rounded-lg bg-[#f4faf7] p-3 text-xs text-[#52736a]"><p>{copy.coreKey}: <code>{core.key}</code></p><p className="mt-1">{copy.valueType}: <code>{field.valueType}</code></p>{taxonomySemantic ? <><p className="mt-1">{copy.semanticRenderer}: <code>{runtimeSourced ? copy.taxonomySelect : field.renderer}</code></p><p className="mt-1">{taxonomySemantic.description}</p></> : null}{core.requiredByDomain ? <p className="mt-1">{copy.domainRequired}</p> : null}{!rendererCanChange ? <p className="mt-1">{copy.rendererLocked}</p> : null}<p className="mt-1">{copy.coreKeyLocked}</p></div> : <p className="mt-3 text-xs text-[#52736a]">{copy.valueType}: <code>{field.valueType}</code></p>}
    {core && !taxonomySemantic && !core.allowedRenderers.includes(field.renderer) ? <button type="button" onClick={() => onChange({ renderer: core.defaultRenderer, valueType: core.valueType })} className="mt-3 rounded-full border border-[#cfe0d8] px-3 py-1.5 text-sm font-bold text-[#1f6a58]">Use registry renderer: {core.defaultRenderer}</button> : null}
    {core && core.requiredByDomain && !field.required ? <button type="button" onClick={() => onChange({ required: true })} className="mt-3 rounded-full border border-[#cfe0d8] px-3 py-1.5 text-sm font-bold text-[#1f6a58]">Mark required by Event domain</button> : null}
    {core && compositeDefinition ? <CompositeFieldEditor field={field} core={core} definition={compositeDefinition} onChange={onChange} /> : <><div className="mt-4 grid gap-3 sm:grid-cols-2">{!core || core.configurable.label ? <TextControl label={copy.label} value={field.label} onChange={(label) => onChange({ label })} /> : null}{rendererCanChange ? <SelectControl label={copy.renderer} value={field.renderer} onChange={(renderer) => onChange({ renderer: renderer as FormRenderer })} options={allowedRenderers.map((renderer) => [renderer, copy.fieldTypes[renderer as keyof typeof copy.fieldTypes] ?? renderer])} /> : null}{!core || core.configurable.placeholder ? <TextControl label={copy.placeholder} value={field.placeholder} onChange={(placeholder) => onChange({ placeholder })} /> : null}{!core || core.configurable.helpText ? <TextControl label={copy.helpText} value={field.helpText} onChange={(helpText) => onChange({ helpText })} /> : null}{!core || core.configurable.required ? <label className="flex items-center gap-2 pt-6 text-sm text-[#355a51]"><input type="checkbox" checked={field.required} disabled={Boolean(core?.requiredByDomain && field.required)} onChange={(event) => onChange({ required: core?.requiredByDomain ? true : event.target.checked })} />{copy.required}</label> : null}<label className="flex items-center gap-2 pt-6 text-sm text-[#355a51]"><input type="checkbox" checked={field.enabled} disabled={Boolean(core && !core.hideable)} onChange={(event) => onChange({ enabled: event.target.checked })} />{copy.enabled}</label></div>{(!core || core.configurable.validation) && textValidation ? <ValidationEditor validation={field.validation} onChange={setValidation} text /> : null}{(!core || core.configurable.validation) && numberValidation ? <ValidationEditor validation={field.validation} onChange={setValidation} /> : null}{(!runtimeSourced && (field.renderer === "select" || field.renderer === "multi_select")) ? <OptionEditor options={field.options} onChange={(options) => onChange({ options: normalizeOptionPositions(options) })} onUpdate={updateOption} onMove={moveOption} /> : null}</>}
  </article>;
}

function ValidationEditor({ validation, onChange, text = false }: { validation: FormFieldValidation; onChange: (patch: Partial<FormFieldValidation>) => void; text?: boolean }) {
  const [advancedOpen, setAdvancedOpen] = useState(Boolean(validation.pattern));
  if (!text) return <fieldset className="mt-4 grid gap-3 rounded-xl border border-[#edf3f0] p-3 sm:grid-cols-2"><legend className="px-1 text-sm font-semibold text-[#355a51]">{copy.validation}</legend><NumberControl label={copy.minimum} value={validation.min} onChange={(min) => onChange({ min })} /><NumberControl label={copy.maximum} value={validation.max} onChange={(max) => onChange({ max })} /></fieldset>;
  const minInvalid = validation.minLength !== null && validation.minLength !== undefined && validation.minLength < 0;
  const maxInvalid = validation.maxLength !== null && validation.maxLength !== undefined && validation.maxLength < 0;
  const rangeInvalid = validation.minLength !== null && validation.maxLength !== null && validation.minLength !== undefined && validation.maxLength !== undefined && validation.minLength > validation.maxLength;
  let patternInvalid = false; try { if (validation.pattern) new RegExp(validation.pattern); } catch { patternInvalid = true; }
  return <fieldset className="mt-4 rounded-xl border border-[#edf3f0] p-3"><legend className="px-1 text-sm font-semibold text-[#355a51]">{copy.validation}</legend><p className="mb-3 text-xs font-normal text-[#52736a]">{copy.validationIntro}</p><div className="grid gap-3 sm:grid-cols-2"><NumberControl label={copy.minLength} placeholder="e.g. 3" value={validation.minLength} onChange={(minLength) => onChange({ minLength })} /><NumberControl label={copy.maxLength} placeholder="e.g. 100" value={validation.maxLength} onChange={(maxLength) => onChange({ maxLength })} /></div>{minInvalid ? <p className="mt-2 text-xs font-semibold text-[#b42318]">Minimum characters cannot be less than 0.</p> : null}{maxInvalid ? <p className="mt-2 text-xs font-semibold text-[#b42318]">Maximum characters cannot be less than 0.</p> : null}{rangeInvalid ? <p className="mt-2 text-xs font-semibold text-[#b42318]">Minimum characters cannot be greater than maximum characters.</p> : null}<button type="button" aria-expanded={advancedOpen} onClick={() => setAdvancedOpen((open) => !open)} className="mt-3 text-sm font-semibold text-[#1f6a58]">{advancedOpen ? "Advanced validation" : "Advanced validation ›"}</button>{advancedOpen ? <div className="mt-3 border-t border-[#edf3f0] pt-3"><TextControl label={copy.pattern} placeholder="e.g. ^[A-Za-z ]+$" value={validation.pattern ?? ""} onChange={(pattern) => onChange({ pattern: pattern || null })} /><p className="mt-1 text-xs font-normal text-[#52736a]">{copy.patternHelp}</p><p className="mt-1 text-[11px] font-normal text-[#7f9d94]">{copy.patternNote}</p><p className="mt-1 text-[11px] font-normal text-[#7f9d94]">Example: ^[A-Za-z ]+$ — Allows letters and spaces only.</p>{patternInvalid ? <p className="mt-1 text-xs font-semibold text-[#b42318]">This format rule is not valid. Check the pattern and try again.</p> : null}</div> : null}</fieldset>;
}
function makeOptionValue(label: string, options: readonly FormFieldOption[], currentIndex: number): string { const base = label.toLowerCase().trim().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "option"; let value = base; let suffix = 2; while (options.some((option, index) => index !== currentIndex && option.value === value)) value = `${base}_${suffix++}`; return value; }
function OptionEditor({ options, onChange, onUpdate, onMove }: { options: FormFieldOption[]; onChange: (options: FormFieldOption[]) => void; onUpdate: (index: number, patch: Partial<FormFieldOption>) => void; onMove: (index: number, amount: number) => void }) { return <fieldset className="mt-4 min-w-0 rounded-xl border border-[#edf3f0] p-3"><legend className="px-1 text-sm font-semibold text-[#355a51]">{copy.options}</legend><div className="min-w-0 space-y-2">{options.map((option, index) => <div key={`option-${index}`} className="grid min-w-0 grid-cols-1 gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><input aria-label={copy.optionLabel} value={option.label} onChange={(event) => onUpdate(index, { label: event.target.value, ...(option.value ? {} : { value: makeOptionValue(event.target.value, options, index) }) })} className="min-w-0 w-full rounded-lg border border-[#cfe0d8] px-2 py-1.5 text-sm" /><button type="button" aria-label={copy.delete} title={copy.delete} onClick={() => onChange(options.filter((_, itemIndex) => itemIndex !== index))} className="text-sm font-semibold text-[#b42318]">Remove</button></div>)}</div><button type="button" onClick={() => { const label = copy.newOption; onChange([...options, { label, value: makeOptionValue(label, options, -1), position: options.length + 1 }]); }} className="mt-3 text-sm font-bold text-[#1f6a58]">{copy.addOption}</button></fieldset>; }
function TextControl({ label, value, placeholder, onChange }: { label: string; value: string; placeholder?: string; onChange: (value: string) => void }) { return <label className="text-sm font-semibold text-[#355a51]"><span>{label}</span><input value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#cfe0d8] px-3 py-2 font-normal" /></label>; }
function NumberControl({ label, value, placeholder, onChange }: { label: string; value: number | null | undefined; placeholder?: string; onChange: (value: number | null) => void }) { return <label className="text-sm font-semibold text-[#355a51]"><span>{label}</span><input type="number" placeholder={placeholder} value={value ?? ""} onChange={(event) => onChange(event.target.value === "" ? null : Number(event.target.value))} className="mt-1.5 w-full rounded-lg border border-[#cfe0d8] px-3 py-2 font-normal" /></label>; }
function SelectControl({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: readonly (readonly [string, string])[] }) { return <label className="text-sm font-semibold text-[#355a51]"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#cfe0d8] bg-white px-3 py-2 font-normal">{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></label>; }
