"use client";

import { DndContext, KeyboardSensor, PointerSensor, closestCenter, type CollisionDetection, useDroppable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { formConfigurationCopy as copy } from "../constants/form-configuration-copy";
import { getEventCoreFieldSemantic } from "../model/event-core-field-semantics";
import type { ConfiguredField, FormSection } from "../model/form-configuration.types";

export type BuilderSelection = { kind: "section" | "field"; id: string } | null;
type DragKind = "section" | "field" | "field-drop";
type CanvasProps = { sections: readonly FormSection[]; fields: readonly ConfiguredField[]; selected: BuilderSelection; onSelect: (selection: BuilderSelection) => void; onAddSection: () => void; onAddField: (sectionLocalId: string) => void; onSectionAction: (localId: string, action: "duplicate" | "toggle" | "delete") => void; onDragEnd: (event: DragEndEvent) => void };

function Handle() { return <span aria-hidden="true" className="select-none text-base leading-none text-[#8ca69e]">⠿</span>; }

function FieldRow({ field, selected, onSelect }: { field: ConfiguredField; selected: boolean; onSelect: () => void }) {
  const sortable = useSortable({ id: `field-${field.localId}`, data: { dragKind: "field" satisfies DragKind } });
  const taxonomySemantic = field.source === "core" ? getEventCoreFieldSemantic(field.coreKey) : undefined;
  const rendererLabel = taxonomySemantic ? copy.taxonomySelect : copy.fieldTypes[field.renderer as keyof typeof copy.fieldTypes] ?? field.renderer;
  return <button ref={sortable.setNodeRef} {...sortable.attributes} type="button" onPointerDown={(event) => event.stopPropagation()} onClick={onSelect} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition }} className={`flex w-full items-center gap-3 rounded-xl border p-2.5 text-left transition ${selected ? "border-[#1f6a58] bg-[#e9f4ee]" : "border-[#edf3f0] bg-white hover:border-[#b9d4c8]"}`}><span {...sortable.listeners} onClick={(event) => event.stopPropagation()} aria-label={copy.moveUp} className="cursor-grab touch-none"><Handle /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[#06201c]">{field.label}</span><span className="block text-xs text-[#52736a]">{rendererLabel} · {field.required ? copy.required : copy.optional}</span></span><span className="rounded-full bg-[#eef6f2] px-2 py-0.5 text-[10px] font-bold uppercase text-[#176347]">{field.source === "core" ? copy.core : copy.custom}</span></button>;
}

function EmptyDropZone({ sectionLocalId }: { sectionLocalId: string }) { const drop = useDroppable({ id: `drop-${sectionLocalId}`, data: { dragKind: "field-drop" satisfies DragKind } }); return <div ref={drop.setNodeRef} onPointerDown={(event) => event.stopPropagation()} className="rounded-xl border border-dashed border-[#cfe0d8] px-3 py-3 text-center text-xs text-[#7f9d94]">{copy.noFields}</div>; }

function SectionCard({ section, number, fields, selected, selectedFieldId, onSelect, onSelectField, onAddField, onAction }: { section: FormSection; number: number; fields: readonly ConfiguredField[]; selected: boolean; selectedFieldId: string | null; onSelect: () => void; onSelectField: (localId: string) => void; onAddField: () => void; onAction: CanvasProps["onSectionAction"] }) {
  const sortable = useSortable({ id: `section-${section.localId}`, data: { dragKind: "section" satisfies DragKind } }); const ordered = [...fields].sort((left, right) => left.position - right.position);
  return <article ref={sortable.setNodeRef} {...sortable.attributes} {...sortable.listeners} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition }} className={`rounded-2xl border bg-white p-4 shadow-sm ${selected ? "border-[#1f6a58] ring-2 ring-[#d6eee2]" : "border-[#dfe9e4]"}`}><div className="flex gap-3"><span aria-label={copy.moveUp} className="mt-1 cursor-grab touch-none"><Handle /></span><button type="button" onClick={onSelect} className="min-w-0 flex-1 text-left"><span className="font-bold text-[#06201c]">{copy.sectionNumber.replace("{number}", String(number))} {section.name}</span><span className={`ml-2 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${section.enabled ? "bg-[#e8f6ee] text-[#176347]" : "bg-[#f1f4f3] text-[#587067]"}`}>{section.enabled ? copy.enabled : copy.disabled}</span>{section.description ? <span className="mt-1 block text-sm text-[#52736a]">{section.description}</span> : null}<span className="mt-1 block text-xs text-[#7f9d94]">{copy.fieldCount.replace("{count}", String(ordered.length))}</span></button><details onPointerDown={(event) => event.stopPropagation()} className="relative"><summary aria-label={copy.moreActions} className="cursor-pointer list-none rounded-lg border border-[#dfe9e4] px-2 py-1 text-[#52736a]">•••</summary><div className="absolute right-0 z-10 mt-1 w-40 rounded-xl border border-[#dfe9e4] bg-white p-1 shadow-lg"><button type="button" onClick={onSelect} className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-[#f4faf7]">{copy.editSection}</button><button type="button" onClick={() => onAction(section.localId, "duplicate")} className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-[#f4faf7]">{copy.duplicateSection}</button><button type="button" onClick={() => onAction(section.localId, "toggle")} className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-[#f4faf7]">{section.enabled ? copy.disabled : copy.enabled}</button><button type="button" onClick={() => onAction(section.localId, "delete")} className="w-full rounded-lg px-3 py-2 text-left text-sm text-[#b42318] hover:bg-[#fff5f4]">{copy.delete}</button></div></details></div><div className="mt-3 space-y-2 pl-6"><SortableContext items={ordered.map((field) => `field-${field.localId}`)} strategy={verticalListSortingStrategy}>{ordered.map((field) => <FieldRow key={field.localId} field={field} selected={selectedFieldId === field.localId} onSelect={() => onSelectField(field.localId)} />)}</SortableContext>{ordered.length === 0 ? <EmptyDropZone sectionLocalId={section.localId} /> : null}<button type="button" onPointerDown={(event) => event.stopPropagation()} onClick={onAddField} className="text-sm font-bold text-[#1f6a58]">{copy.addField}</button></div></article>;
}

const collisionDetection: CollisionDetection = (args) => { const activeKind = args.active.data.current?.dragKind as DragKind | undefined; const droppableContainers = args.droppableContainers.filter((container) => { const dropKind = container.data.current?.dragKind as DragKind | undefined; return activeKind === "section" ? dropKind === "section" : dropKind === "field" || dropKind === "field-drop"; }); return closestCenter({ ...args, droppableContainers }); };

/** Renders the compact nested builder canvas; review is deliberately outside the sortable list. */
export function FormStructureCanvas({ sections, fields, selected, onSelect, onAddSection, onAddField, onSectionAction, onDragEnd }: CanvasProps) {
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates })); const orderedSections = [...sections].sort((left, right) => left.position - right.position);
  return <section className="rounded-2xl border border-[#dfe9e4] bg-[#f7fbf8] p-4"><h3 className="text-sm font-bold uppercase tracking-[.14em] text-[#52736a]">{copy.formStructure}</h3><DndContext sensors={sensors} collisionDetection={collisionDetection} onDragEnd={onDragEnd}><SortableContext items={orderedSections.map((section) => `section-${section.localId}`)} strategy={verticalListSortingStrategy}><div className="mt-4 space-y-3">{orderedSections.map((section, index) => <SectionCard key={section.localId} section={section} number={index + 1} fields={fields.filter((field) => field.sectionLocalId === section.localId)} selected={selected?.kind === "section" && selected.id === section.localId} selectedFieldId={selected?.kind === "field" ? selected.id : null} onSelect={() => onSelect({ kind: "section", id: section.localId })} onSelectField={(localId) => onSelect({ kind: "field", id: localId })} onAddField={() => onAddField(section.localId)} onAction={onSectionAction} />)}</div></SortableContext></DndContext><button type="button" onClick={onAddSection} className="mt-4 rounded-full border border-[#cfe0d8] bg-white px-4 py-2 text-sm font-bold text-[#1f6a58]">{copy.addSection}</button><article className="mt-4 rounded-xl border border-dashed border-[#cfe0d8] bg-white p-4"><p className="font-semibold text-[#06201c]">{copy.sectionNumber.replace("{number}", String(orderedSections.length + 1))} {copy.reviewSubmit}</p><p className="mt-1 text-sm text-[#52736a]">{copy.systemStep}</p></article></section>;
}
